HW4: Danil Ivanov
Walingar/java-is-2020 pull request #100
Opened 2020-04-15 17:22 UTC by NeHo4y

2020-04-20 09:05 UTC, Walingar requested changes
Очень хорошо, пофикси небольшие проблемки в имплементации на массиве

2020-04-20 09:05 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +class ArrayQueueImpl<Integer> extends AbstractQueue<Integer> {
Ты тут сделал ArrayQueueImpl с generic параметром, который называется Integer, нужно было написать такое:
`class ArrayQueueImpl extends AbstractQueue<Integer>`
Тогда в методах ниже был бы Integer, как класс, а не как название параметра

2020-04-20 09:05 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +            var newCapacity = (int) (capacity / CAPACITY_FACTOR);
Тут получается, если мы будем добавлять и удалять около 128 элемента, то массив будет постоянно уменьшаться/увеличиваться.
Чтобы этого избежать, нужно проверять, чтобы элементов было capacity / (CAPACITY_FACTOR ^ 2)

2020-04-20 09:05 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        private QueueElement<T> previous;
previous не используется

2020-05-31 15:10 UTC, Walingar requested changes

2020-05-31 15:10 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private Object[] queueElements = new Object[MINIMAL_CAPACITY];
Почему Objects?

2020-05-31 15:10 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +class LinkedQueueImpl<T> extends AbstractQueue<T> {
Почему здесь generic имплементация, а в реализации на массиве нет?

2020-06-17 15:15 UTC, NeHo4y commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +class LinkedQueueImpl<T> extends AbstractQueue<T> {
Так как изначально generic хотел и там и там, но меня очень раздражал uncheck, ну и воркэраунд был просто сделать Integer

2020-06-17 15:16 UTC, NeHo4y commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private Object[] queueElements = new Object[MINIMAL_CAPACITY];
Так как изначально generic хотел, но меня очень раздражал uncheck.

2020-06-20 09:25 UTC, Walingar approved these changes

2020-06-20 09:25 UTC, merged