HW5: Aleksandr Aleksandrov
Walingar/java-is-2020 pull request #105
Opened 2020-04-15 20:31 UTC by AD-Aleksandrov

2020-04-20 10:13 UTC, Walingar requested changes

2020-04-20 10:13 UTC, Walingar commented on src/main/java/impl/file/FileEncodingReaderImpl.java
> +            throw new RuntimeException(e.getMessage());
Не хорошо бросать сырой RuntimeException, лучше бросать что-то более специфичное

2020-04-20 10:13 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +        if (file_dir != null && !file_dir.exists() && !file_dir.mkdirs()){
codestyle

2020-04-20 10:13 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            throw new RuntimeException("Failed to create parent directory");
аналогично

2020-04-20 10:13 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            FileWriter file_stream = new FileWriter(file, fileEncoding);
codestyle

2020-04-20 10:13 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            file_stream.close();
Неправильное закрытие стрима

2020-04-20 10:13 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            throw new RuntimeException(e.getMessage());
аналогично

2020-04-28 19:59 UTC, AD-Aleksandrov commented on src/main/java/impl/file/FileEncodingReaderImpl.java
> +            throw new RuntimeException(e.getMessage());
Полностью согласен, но я подумал что в данном случае это неважно :)
И в интерфейсе нет специфичного исключения, нужно добавлять.

2020-04-28 20:13 UTC, AD-Aleksandrov commented on src/main/java/impl/file/FileEncodingReaderImpl.java
> +            throw new RuntimeException(e.getMessage());
Полность согласен, но в интерфейсе нет специфичного исключения. Мне кажется в данном случае это не очень важно.

2020-05-18 19:56 UTC, Walingar requested changes

2020-05-18 19:56 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +        try (FileWriter file_stream = new FileWriter(file, fileEncoding)) {
code-style

2020-05-18 19:56 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            char []buff = new char[IO_BUFF_SIZE];
code-style

2020-06-30 21:16 UTC, closed without merging