HW4: Kuklin Dmitrii
Walingar/java-is-2020 pull request #106
Opened 2020-04-15 20:32 UTC by Diamindes

2020-04-20 09:31 UTC, Walingar requested changes

2020-04-20 09:31 UTC, Walingar commented on src/main/java/queue/impl/linked/Node.java
> +public class Node {
Это часть имплементации LinkedQueue, поэтому оно должно быть внутри, как nested class

2020-04-20 09:31 UTC, Walingar commented on src/main/java/queue/impl/linked/Node.java
> +  private Integer item;
final

2020-04-20 09:31 UTC, Walingar commented on src/main/java/queue/impl/linked/Node.java
> +  public boolean isHasRemoved() {
Это никак не учитывается в работе LinkedQueue, получается можно получить удаленный элемент с помощью poll

2020-04-20 09:31 UTC, Walingar commented on src/main/java/queue/impl/linked/LinkedQueueImpl.java
> +  private Node head, tail;
Филды и переменные должны создаваться по 1 на строке

2020-04-20 09:31 UTC, Walingar commented on src/main/java/queue/impl/linked/LinkedQueueImpl.java
> +    return this.size;
Без this

2020-04-20 09:31 UTC, Walingar commented on src/main/java/queue/impl/linked/Node.java
> +  private Node prev;
Можно реализовать с помощью односвязного списка и сэкономить память

2020-04-20 09:31 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +  public Integer poll() {
Получается, если мы добавим много элементов, а потом бОльшую часть удалим, то мы все равно будем хранить большой массив - нехорошо

2020-04-20 09:31 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    head = (head + 1) % items.length;
много копипасты вида (x + 1) % items.length

2020-06-30 15:11 UTC, Diamindes commented on src/main/java/queue/impl/linked/Node.java
> +public class Node {
Перенёс Node  и LinkedQueueIterator внутрь. Java подарила нам возможность бить всё на классы и наслаждаться пакетами, но можно всё и в один класс запихать)

2020-06-30 15:12 UTC, Diamindes commented on src/main/java/queue/impl/linked/Node.java
> +  private Integer item;
done

2020-06-30 15:12 UTC, Diamindes commented on src/main/java/queue/impl/linked/LinkedQueueImpl.java
> +    return this.size;
done

2020-06-30 15:12 UTC, Diamindes commented on src/main/java/queue/impl/linked/LinkedQueueImpl.java
> +  private Node head, tail;
done

2020-06-30 15:12 UTC, Diamindes commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    head = (head + 1) % items.length;
done, вынес в метод

2020-06-30 15:13 UTC, Diamindes commented on src/main/java/queue/impl/linked/Node.java
> +  private Node prev;
Можно, но тут  удобнее работать с двусвязным.

2020-06-30 15:15 UTC, Diamindes commented on src/main/java/queue/impl/linked/Node.java
> +  public boolean isHasRemoved() {
Да, криво реализовал, не двигал указатели и размер не менялся. 

В целом это нужно только для удаления по итератору, чтобы кинуть исключения в случае двойного вызова, при poll он не нужен, там всё по указателям ходит.

2020-06-30 15:16 UTC, Diamindes commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +  public Integer poll() {
да, забыл уменьшать. Дополнил resize.

2020-06-30 21:43 UTC, Walingar approved these changes

2020-06-30 21:43 UTC, Walingar approved these changes

2020-06-30 21:43 UTC, merged