HW7: Sukhikh Alexander
Walingar/java-is-2020 pull request #108
Opened 2020-04-16 00:38 UTC by GitCaptain

2020-06-17 14:36 UTC, Walingar requested changes

2020-06-17 14:36 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/Student.java
> +    /**
В этом файле не нужно было делать изменения

2020-06-17 14:36 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentQuery.java
> +    /**
Как и в этом

2020-06-17 14:36 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentQueryImpl.java
> +    private <T> Collection<T> getSortedCollection(Collection<T> collection, Comparator<T> comparator) {
Коллекция по своему интерфейсу не может быть sorted

2020-06-17 14:36 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentQueryImpl.java
> +        return (List<String>) getMappedCollection(students, Student::getFirstName);
Не надо делать такие касты. Следует или создавать new ArrayList(getMapped...). Или сделать так, чтобы метод возвращал List (в данном случае так лучше будет)

2020-06-20 11:10 UTC, GitCaptain commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentQuery.java
> +    /**
там ж только комментарии поменялись. эт важно? Их ide сама поменяла во время форматирования.

2020-06-20 13:33 UTC, Walingar approved these changes

2020-06-20 13:33 UTC, merged