HW4: Korzhov Andrew
Walingar/java-is-2020 pull request #111
Opened 2020-04-16 09:41 UTC by Andy1897

2020-04-20 09:41 UTC, Walingar requested changes

2020-04-20 09:41 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    private int coefficient;
final. И это даже можно сделать константой

2020-04-20 09:41 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    private class ArrayQueueIterator implements Iterator {
raw type

2020-04-20 09:41 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    private class ArrayQueueIterator implements Iterator {
Лучше nested классы в в конце писать

2020-04-20 09:41 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +        queue[end] = (Integer) item;
Тут не нужен каст

2020-04-20 09:41 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +        if (size() == 0) {
Почему в методе выше size, а здесь size()

2020-04-20 09:41 UTC, Walingar commented on src/main/java/queue/impl/QueueLinkedImpl.java
> +        void setValue(int newValue) {
unused method

2020-04-20 09:41 UTC, Walingar commented on src/main/java/queue/impl/QueueLinkedImpl.java
> +    private static class Item {
тоже в конце лучше писать класс

2020-04-20 09:41 UTC, Walingar commented on src/main/java/queue/impl/QueueLinkedImpl.java
> +    private static class LinkedQueueIterator implements Iterator {
Не нужно использовать Raw Types

2020-04-20 09:41 UTC, Walingar commented on src/main/java/queue/impl/QueueLinkedImpl.java
> +        LinkedQueueIterator(Item head) {
Отступ в одну пустую строчку должен быть перед конструктором

2020-04-20 09:41 UTC, Walingar commented on src/main/java/queue/impl/QueueLinkedImpl.java
> +            return next;
Можно сразу сделать return current.getNext()

2020-05-19 09:47 UTC, Andy1897 commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    private class ArrayQueueIterator implements Iterator {
Поправил

2020-05-19 09:47 UTC, Andy1897 commented on src/main/java/queue/impl/QueueArrayImpl.java
> +        queue[end] = (Integer) item;
Поправил

2020-05-19 09:47 UTC, Andy1897 commented on src/main/java/queue/impl/QueueArrayImpl.java
> +        if (size() == 0) {
Поправил

2020-05-19 09:47 UTC, Andy1897 commented on src/main/java/queue/impl/QueueLinkedImpl.java
> +    private static class LinkedQueueIterator implements Iterator {
Поправил

2020-05-19 09:48 UTC, Andy1897 commented on src/main/java/queue/impl/QueueLinkedImpl.java
> +        LinkedQueueIterator(Item head) {
Поправил

2020-05-19 09:49 UTC, Andy1897 commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    private int coefficient;
Поправил

2020-05-19 09:49 UTC, Andy1897 commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    private class ArrayQueueIterator implements Iterator {
Поправил

2020-05-31 15:23 UTC, Walingar requested changes

2020-05-31 15:23 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +public class QueueArrayImpl extends AbstractQueue<Integer> {
Не выполнено условие задания
> Постарайтесь сделать так, чтобы при длинной цепочке действий add(element), poll программа не потребляла много памяти.

2020-05-31 15:23 UTC, Walingar commented on src/main/java/queue/impl/QueueLinkedImpl.java
> +    private static class LinkedQueueIterator implements Iterator<Item> {
nested классы должны быть внизу

2020-05-31 15:23 UTC, Walingar commented on src/main/java/queue/impl/QueueLinkedImpl.java
> +        private Integer value;
Вы планируете менять значение?

2020-05-31 15:23 UTC, Walingar commented on src/main/java/queue/impl/QueueLinkedImpl.java
> +            this.nextItem = next;
Нужен ли здесь this?

2020-05-31 15:23 UTC, Walingar commented on src/main/java/queue/impl/QueueLinkedImpl.java
> +    private static class Item {
Item? Точно ли это хорошее название? Что вы под ним подразумеваете?

2020-06-17 10:58 UTC, Walingar approved these changes

2020-06-17 10:58 UTC, merged