HW:5 Korzhov Andrew
Walingar/java-is-2020 pull request #119
Opened 2020-04-16 19:51 UTC by Andy1897

2020-04-20 10:18 UTC, Walingar requested changes

2020-04-20 10:18 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +                file.getParentFile().mkdirs();
Не очень хорошо игнорировать результаты mkdirs и createNewFile. Что если не получилось? Сможем ли мы продолжить выполнение дальше?

2020-05-19 09:49 UTC, Andy1897 commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +                file.getParentFile().mkdirs();
Поправил

2020-05-31 15:16 UTC, Walingar approved these changes

2020-05-31 15:16 UTC, merged