HW5: Kuklin Dmitrii
Walingar/java-is-2020 pull request #121
Opened 2020-04-16 20:39 UTC by Diamindes

2020-04-20 10:21 UTC, Walingar requested changes

2020-04-20 10:21 UTC, Walingar commented on src/main/java/impl/file/FileEncodingReaderImpl.java
> +      throw new RuntimeException(e);
Не хорошо бросать сырой RuntimeException, лучше бросать что-то более специфичное

2020-04-20 10:21 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +      throw new RuntimeException(e);
аналогично

2020-04-20 10:21 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +    file.createNewFile();
Не очень хорошо игнорировать результат этих операций. А что если мы не смогли создать файл? Сможем ли мы продолжить работу?

2020-06-30 15:17 UTC, Diamindes commented on src/main/java/impl/file/FileEncodingReaderImpl.java
> +      throw new RuntimeException(e);
done, добавил обёртку UncheckedIOException

2020-06-30 15:18 UTC, Diamindes commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +      throw new RuntimeException(e);
done

2020-06-30 15:18 UTC, Diamindes commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +    file.createNewFile();
done

2020-06-30 21:52 UTC, Walingar approved these changes

2020-06-30 21:52 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +    file.getParentFile().mkdirs();
проигнорирован результат создания директорий, но ок

2020-06-30 21:53 UTC, merged

2020-06-30 21:53 UTC, Walingar approved these changes