Done task 4
Walingar/java-is-2020 pull request #122
Opened 2020-04-16 20:46 UTC by Eduard585

2020-04-20 09:52 UTC, Walingar requested changes

2020-04-20 09:52 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        int newCapacity = oldCapacity/CAPACITY_RATE;
spaces

2020-04-20 09:52 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        int newCapacity = oldCapacity + (oldCapacity >> 1);
Делить на 2 лучше с помощью деления на 2)

2020-04-20 09:52 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +public class ArrayQueueImpl<Integer> extends AbstractQueue<Integer> {
Ты тут сделал generic параметр, с названием Integer
Нужно сделать `public class ArrayQueueImpl extends AbstractQueue<Integer>`
Тогда не нужны будут касты

2020-04-20 09:52 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private Object[] elements;
И можно будет сделат массив Integer

2020-04-20 09:52 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        if (head > capacity - capacity / CAPACITY_RATE) {
Получается, после уменьшения размера, если мы будем делать poll/add то постоянно будем уменьшать, увеличивать размер массива, не хорошо. В таком случае делают так, чтобы после уменьшения размера массива, в нем оставалось элементов capacity / CAPACITY_RATE

2020-04-20 09:52 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        return null;
Забыл создать итератор)

2020-04-20 09:52 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    private class LinkedQueueIterator implements Iterator<T>{
Забыл имплементировать итератор )

2020-04-20 09:52 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    private static class Node<T>{
пробел

2020-04-20 09:52 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        public  Node<T> nextNode;
лишний пробел

2020-04-27 19:38 UTC, Eduard585 commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        int newCapacity = oldCapacity + (oldCapacity >> 1);
![image](https://user-images.githubusercontent.com/33941067/80413124-a2dd9c00-88d7-11ea-9850-cc60e6760b1d.png)
Я подсмотрел в priorityQueue) Если честно не разобрался в вопросе) Почему в имплементации так?

2020-04-27 21:17 UTC, Eduard585 commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        if (head > capacity - capacity / CAPACITY_RATE) {
@Walingar как я правильно понял, проблема в том, что мы начинаем туда сюда скакать после shrink т.к. head после shrink находится на границе определенной с помощью CAPACITY_RATE.  И решение в том, чтобы уменьшать массив не настолько сильно, чтобы head был подальше от границы? Т.е. чтобы tail - head  = newCapacity/CAPACITY_RATE?

2020-05-19 07:45 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        int newCapacity = oldCapacity + (oldCapacity >> 1);
Скорее всего, тому, кто писал реализацию, просто привычнее так писать деление на 2

2020-05-19 07:45 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        int newCapacity = oldCapacity + (oldCapacity >> 1);
Но лучше писать это `/ 2`, так будет проще понимать твой код большенству разработчиков

2020-05-19 07:48 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        if (head > capacity - capacity / CAPACITY_RATE) {
> чтобы tail - head = newCapacity/CAPACITY_RATE

Да, все верно

2020-05-19 07:51 UTC, Walingar requested changes

2020-05-19 07:51 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +import org.jetbrains.annotations.NotNull;
лишний импорт

2020-05-19 07:51 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        if (head > capacity - capacity / CAPACITY_RATE) {
Этот момент поправь и ок)

2020-06-30 21:44 UTC, Walingar approved these changes

2020-06-30 21:44 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +                throw ex;
Непонятно, зачем ловить исключение, если оно сразу бросается и другие не ловятся

2020-06-30 21:45 UTC, merged