Task 6 my repo
Walingar/java-is-2020 pull request #133
Opened 2020-04-22 19:23 UTC by ITLeopard

2020-05-19 07:57 UTC, Walingar commented
Много лишних коммитов в пулл реквесте, убери их, пожалуйста

2020-05-19 07:57 UTC, Walingar requested changes
Много лишних коммитов в пулл реквесте, убери их, пожалуйста

2020-06-17 11:22 UTC, Walingar requested changes

2020-06-17 11:22 UTC, Walingar commented on src/main/java/impl/pair/PairImpl.java
> +    public boolean equals(Object obj) {
Метод сложен в понимании. Лучше стараться как можно меньше использовать mutable переменные.

2020-06-17 11:22 UTC, Walingar commented on src/main/java/impl/pair/PairImpl.java
> +            result = first.toString().equals(temp.getFirst().toString()) && second.toString().equals(temp.getSecond().toString());
Сравнивать пары как строки -- плохая идея. Что если первые элементы у пар разные, а строки у них одинаковые?

2020-06-17 11:22 UTC, Walingar commented on src/main/java/impl/pair/NumberPairImpl.java
> +public class NumberPairImpl<K, T> extends PairImpl<K, T> {
Не выполнено условие задания

2020-06-17 12:11 UTC, ITLeopard commented on src/main/java/impl/pair/NumberPairImpl.java
> +public class NumberPairImpl<K, T> extends PairImpl<K, T> {
Какое условие не выполнено? Значения first и second должны быть полями класса NumberPairImpl?

2020-06-17 13:56 UTC, Walingar commented on src/main/java/impl/pair/NumberPairImpl.java
> +public class NumberPairImpl<K, T> extends PairImpl<K, T> {
Ваша задача разработать реализации интерфейсов `api.pair.Pair` и `api.pair.NumberPair `и уметь создавать их в методах `impl.pair.PairFactory.of` и `impl.pair.NumberPairFactory.of` соответственно. Пары хранят в себе два значения first и second.

2020-06-17 13:57 UTC, ITLeopard commented on src/main/java/impl/pair/NumberPairImpl.java
> +public class NumberPairImpl<K, T> extends PairImpl<K, T> {
Это я читала.

2020-06-17 14:00 UTC, Walingar commented on src/main/java/impl/pair/NumberPairImpl.java
> +public class NumberPairImpl<K, T> extends PairImpl<K, T> {
NumberPairImpl реализует интерфейс `api.pair.NumberPair` ?

2020-06-17 14:05 UTC, ITLeopard commented on src/main/java/impl/pair/NumberPairImpl.java
> +public class NumberPairImpl<K, T> extends PairImpl<K, T> {
Понятно. Спасибо, я бы сама не заметила этой ошибки

2020-06-18 10:18 UTC, ITLeopard commented on src/main/java/impl/pair/PairImpl.java
> +    public boolean equals(Object obj) {
Почему ты другому человеку зачел с такой же проблемой, а мне сказал это исправлять?
![image](https://user-images.githubusercontent.com/39529291/85008503-bf72b380-b165-11ea-8ba0-701a2409906b.png)

2020-06-18 10:32 UTC, Walingar commented on src/main/java/impl/pair/PairImpl.java
> +    public boolean equals(Object obj) {
Что ты считаешь такой же проблемой? Какая проблема у тебя? Какая проблема у Сергея?

2020-06-18 10:40 UTC, ITLeopard commented on src/main/java/impl/pair/PairImpl.java
> +    public boolean equals(Object obj) {
Мне обязательно это исправлять?

2020-06-18 10:42 UTC, Walingar commented on src/main/java/impl/pair/PairImpl.java
> +    public boolean equals(Object obj) {
Для начала надо ответить на вопрос

2020-06-18 11:26 UTC, ITLeopard commented on src/main/java/impl/pair/PairImpl.java
> +    public boolean equals(Object obj) {
Этот вопрос? "Что ты считаешь такой же проблемой? Какая проблема у тебя? Какая проблема у Сергея?"
Проблема у меня: в методе я использую mutable переменную Object obj. Сергей тоже использует такую переменную, следовательно, в его коде есть такая же проблема.

2020-06-18 11:27 UTC, Walingar commented on src/main/java/impl/pair/PairImpl.java
> +    public boolean equals(Object obj) {
Начнем с того, что obj -- это аргумент. Что в твоем понимании означает mutable переменная?

2020-06-18 11:38 UTC, ITLeopard commented on src/main/java/impl/pair/PairImpl.java
> +    public boolean equals(Object obj) {
Это переменная, которая может принимать разные по смыслу значения - в моем случае, как я поняла, obj имеет слишком общий вид.
Сейчас посмотрела на код внимательнее - ты про переменную result? Меня так учили делать - если нужно несколько return, то лучше создать отдельную переменную, но return сделать один раз.

2020-06-18 11:41 UTC, Walingar commented on src/main/java/impl/pair/PairImpl.java
> +    public boolean equals(Object obj) {
mutable переменная -- это переменная, которая может принимать различные значения. obj принимает одно единственное значение, которое передали в этот метод. Оно и должно иметь общий вид, чтобы можно было сравнивать твою пару с любыми другими типами.
Да, я говорю о переменной result. Как преподаватели объясняли такой выбор? Почему лучше делать один return с разными значениями?

2020-06-18 11:50 UTC, ITLeopard commented on src/main/java/impl/pair/PairImpl.java
> +    public boolean equals(Object obj) {
Объясняли так: чтобы не надо было искать по всему методу/функции досрочный выход из данного блока кода. Ну и там был еще один весьма весомый аргумент - на блоксхеме так выглядит красивее :D  Про это только сейчас вспомнила, просто засело в голове, что надо делать так :)

2020-06-18 11:54 UTC, Walingar commented on src/main/java/impl/pair/PairImpl.java
> +    public boolean equals(Object obj) {
> не надо было искать по всему методу/функции досрочный выход из данного блока кода

Но с текущим решением нужно не просто смотреть на досрочные выходы, а следить за всеми изменениями переменной. Например: чтобы понять, какой результат будет, если ссылки у this и у obj одинаковые, нужно прочитать весь код метода.

> блоксхеме так выглядит красивее

В это я тоже не верю. На блок схеме это будут обычные стрелки, ведущие к выходу, а не куча ненужных блоков с присвоениями чего-то в result

2020-06-18 12:06 UTC, ITLeopard commented on src/main/java/impl/pair/PairImpl.java
> +    public boolean equals(Object obj) {
Может быть. Честно говоря, я уже забыла все эти странные правила по оформлению блоксхем как страшный сон.

Ок, я поняла, что доп переменную в этом случае использовать не стоит. Спасибо за потраченное на меня время :)

2020-06-20 09:27 UTC, Walingar approved these changes

2020-06-20 09:27 UTC, merged