HW6: Kuklin Dmitrii
Walingar/java-is-2020 pull request #141
Opened 2020-04-23 18:09 UTC by Diamindes

2020-05-19 08:04 UTC, Walingar requested changes

2020-05-19 08:04 UTC, Walingar commented on src/main/java/api/pair/Pair.java
> +
Зачем добавление этой строки?

2020-06-30 15:20 UTC, Diamindes commented on src/main/java/api/pair/Pair.java
> +
Вообще я думал это из Google code style пришло, но это из java convention:

Two blank lines should always be used in the following circumstances:
• Between sections of a source file
• Between class and interface definitions

2020-06-30 21:57 UTC, Walingar approved these changes

2020-06-30 21:57 UTC, merged