HW7: Klemesheva Alexandra
Walingar/java-is-2020 pull request #146
Opened 2020-04-28 17:41 UTC by ITLeopard

2020-06-17 14:38 UTC, Walingar requested changes

2020-06-17 14:38 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueFactory.java
> +public class ArrayQueueFactory {
Эти файлы тут не нужны

2020-06-17 14:38 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +public class StudentDB implements StudentQuery {
Следует вынести общие части методов

2020-06-20 09:32 UTC, Walingar requested changes

2020-06-20 09:32 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +                .distinct()
Для чего нужен distinct?

2020-06-20 09:32 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +                .map(s -> s.getFirstName() + " " + s.getLastName())
можно ли использовать getInfo тут?

2020-06-20 09:32 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +                .stream()
stream чаще всего оставляют на той же строке, что и students, но это тоже зависит от команды, можешь исправлять, можешь не исправлять

2020-06-20 09:32 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +                .sorted(Comparator.comparing(Student::getId))
sorted + limit(1) есть ли другая штука, которая делает это же?

2020-06-20 09:32 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +                .sorted(Comparator.comparing(s -> s.getLastName() + " " + s.getFirstName() + " " + s.getId()))
Нужна ли сортировка?

2020-06-20 09:45 UTC, ITLeopard commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +                .distinct()
Для того, чтобы убрать повторяющиеся элементы списка

2020-06-20 10:01 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +                .distinct()
А потом сделать из этого Set?

2020-06-20 13:37 UTC, Walingar approved these changes

2020-06-20 13:37 UTC, merged