HW5: Semenkin Eduard
Walingar/java-is-2020 pull request #147
Opened 2020-04-28 18:02 UTC by Eduard585

Посмотрел как у других сделано, решение конечно похожее единственное что я не понял, почему если мы в reader возвращаем bufferedReader для перфоманса, то почему бы при записи не использовать буфер и я это сделал) Это дало небольшой прирост для самого долгого теста в среднем на 0.05 мс

2020-06-17 13:05 UTC, Walingar requested changes

2020-06-17 13:05 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            while((numRead = reader.read(charArray,0,2048)) >= 0){
code-style

2020-06-17 13:05 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            char[] charArray = new char[2048];
Следует вынести размер массива

2020-06-17 13:05 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            file.createNewFile();
А что если не получилось создать файл?

2020-06-24 22:56 UTC, Eduard585 commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            file.createNewFile();
То кидаем исключение, пишем в консоль ошибку

2020-06-25 09:04 UTC, Walingar requested changes

2020-06-25 09:04 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            int numRead = 0;
Можно убрать `= 0`, т.к. оно не используется

2020-06-25 09:04 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            file.createNewFile();
Т.е.если метод вернет false, то мы выведем в консоль ошибку?

2020-06-25 09:06 UTC, Eduard585 commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            file.createNewFile();
Надо кидать exception

2020-06-28 07:25 UTC, Eduard585 commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            file.createNewFile();
Хотя я сейчас начал делать, exception кидать не получается т.к. в интерфейсе нет его, можно ретурнить метод

2020-06-30 06:24 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            file.createNewFile();
Можно бросить непроверяемое исключение, его не нужно указывать. Но ты не ответил на вопрос: что произойдет, если метод вернет false?

2020-06-30 21:54 UTC, Walingar approved these changes

2020-06-30 21:54 UTC, merged