HW7: Kuklin Dmitrii
Walingar/java-is-2020 pull request #150
Opened 2020-04-30 14:57 UTC by Diamindes

2020-06-17 14:39 UTC, Walingar requested changes

2020-06-17 14:39 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +public class StudentDB implements StudentQuery {
Следует вынести общие части методов

2020-06-30 15:35 UTC, Diamindes commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +public class StudentDB implements StudentQuery {
done

2020-06-30 21:59 UTC, Walingar approved these changes

2020-06-30 21:59 UTC, merged