HW1: Yushchuk Alexey
Walingar/java-is-2020 pull request #170
Opened 2020-05-27 19:02 UTC by SeptentrionaliumLuminum

Hello Java-IS-2020!

2020-06-17 11:31 UTC, Walingar requested changes
По правилам считается, что PR создан неверно, т.к. тесты не пройдены. Но ладно, исправь историю этого PRа, чтобы в нем были только коммиты с твоим решением первой задачи.

2020-06-17 15:21 UTC, SeptentrionaliumLuminum commented
> 
> 
> По правилам считается, что PR создан неверно, т.к. тесты не пройдены. Но ладно, исправь историю этого PRа, чтобы в нем были только коммиты с твоим решением первой задачи.

Как? Я не могу редактировать PR в части удаления файлов и/или коммитов

2020-06-17 15:25 UTC, Walingar commented
Можешь, изменив ветку в своем репозитории, из которой ты делал PR

2020-06-17 15:37 UTC, SeptentrionaliumLuminum commented
> 
> 
> Можешь, изменив ветку в своем репозитории, из которой ты делал PR

В этом проблема: изначальный репозиторий для Task1 и Task2 скончался; для Task3-Task7 все в порядке. Это, безусловно, мой косяк, который я совершил, пока разбирался с Git'ом.
Можно закрыть эти PR и сделать повторные с аккуратного, целого и красивого репозитория?

2020-06-20 08:48 UTC, Walingar commented
ok сделай

2020-06-20 08:48 UTC, closed without merging