HW4: Maxim Kutimskiy
Walingar/java-is-2020 pull request #177
Opened 2020-05-31 09:11 UTC by maxxkut

2020-06-17 13:34 UTC, Walingar requested changes

2020-06-17 13:34 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private Object[] elements = new Object[MINIMAL_CAPACITY];
Почему Object?

2020-06-19 13:58 UTC, maxxkut commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private Object[] elements = new Object[MINIMAL_CAPACITY];
Согласен, в этом случае не нужно)

2020-06-20 13:40 UTC, Walingar approved these changes

2020-06-20 13:40 UTC, merged