HW2: Sergey Stepanov
Walingar/java-is-2020 pull request #179
Opened 2020-05-31 13:54 UTC by stalker-fc

2020-06-17 13:28 UTC, Walingar requested changes

2020-06-17 13:28 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                if (currentOperator == Operator.ADDITION) {
copy-paste

2020-06-17 13:28 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +    private enum Operator {
nested классы должны быть внизу

2020-06-17 13:44 UTC, stalker-fc commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                if (currentOperator == Operator.ADDITION) {
@Walingar, не до конца понял, в чем суть проблемы, и какие ожидаются от меня исправления.

2020-06-17 13:54 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                if (currentOperator == Operator.ADDITION) {
Суть проблемы, что у тебя присутствует одинаковый кусок кода:
```
if (currentOperator == Operator.ADDITION) {
    result = Math.addExact(result, currentNumber);
} else {
    result = Math.addExact(result, -currentNumber);
}
```
Если ты захочешь его поправить где-то, то нужно будет делать это в двух местах, а не одном. В этом проблема copy-paste подхода

2020-06-20 10:30 UTC, stalker-fc commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                if (currentOperator == Operator.ADDITION) {
@Walingar, fixed

2020-06-20 10:30 UTC, stalker-fc commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +    private enum Operator {
@Walingar, fixed

2020-06-20 21:42 UTC, Walingar approved these changes

2020-06-20 21:42 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                if (!Character.isWhitespace(currentSymbol)) {
else { if {} } -> else if {}

2020-06-20 21:42 UTC, merged