HW3: Stepanov Sergey
Walingar/java-is-2020 pull request #180
Opened 2020-05-31 16:01 UTC by stalker-fc

2020-06-17 13:22 UTC, Walingar requested changes

2020-06-17 13:22 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoImpl.java
> +        int maxDaysInMonth = 0;
Мне кажется, за вас уже реализовали такую функциональность)

2020-06-17 13:22 UTC, Walingar commented on src/main/java/impl/weather/MonthTemperatureStatsImpl.java
> +    private Month month;
final

2020-06-17 13:22 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (monthTemperatureStatsMap.containsKey(month)) {
Получается лишнее обращение к мапе, можно обойтись одним

2020-06-20 10:30 UTC, stalker-fc commented on src/main/java/impl/weather/DayTemperatureInfoImpl.java
> +        int maxDaysInMonth = 0;
@Walingar, fixed

2020-06-20 10:31 UTC, stalker-fc commented on src/main/java/impl/weather/MonthTemperatureStatsImpl.java
> +    private Month month;
fixed

2020-06-20 10:31 UTC, stalker-fc commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (monthTemperatureStatsMap.containsKey(month)) {
fixed

2020-06-25 09:17 UTC, Walingar requested changes

2020-06-25 09:17 UTC, Walingar commented on src/main/java/impl/weather/MonthTemperatureStatsImpl.java
> +    private Map<Integer, DayTemperatureInfo> dayTemperatureInfoMap;
final

2020-06-25 09:17 UTC, Walingar commented on src/main/java/impl/weather/MonthTemperatureStatsImpl.java
> +        dayTemperatureInfoMap = new LinkedHashMap<>();
Можно сразу написать `private final Map<Integer, DayTemperatureInfo> dayTemperatureInfoMap = new LinkedHashMap<>();`

2020-06-25 09:17 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private Map<Month, MonthTemperatureStats> monthTemperatureStatsMap;
final

2020-06-25 09:17 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        monthTemperatureStatsMap = new HashMap<>();
аналогично

2020-06-27 20:41 UTC, Walingar approved these changes

2020-06-27 20:42 UTC, merged