HW4: Stepanov Sergey
Walingar/java-is-2020 pull request #185
Opened 2020-06-01 09:35 UTC by stalker-fc

2020-06-17 13:18 UTC, Walingar requested changes

2020-06-17 13:18 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private class ArrayQueueIterator implements Iterator<Integer> {
nested классы должны быть внизу

2020-06-20 10:31 UTC, stalker-fc commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private class ArrayQueueIterator implements Iterator<Integer> {
@Walingar, fixed

2020-06-25 09:21 UTC, Walingar approved these changes

2020-06-25 09:21 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        } else {
else здесь ну нужно

2020-06-25 09:21 UTC, merged