HW5: Stepanov Sergey
Walingar/java-is-2020 pull request #186
Opened 2020-06-01 10:25 UTC by stalker-fc

2020-06-17 13:14 UTC, Walingar requested changes

2020-06-17 13:14 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +                directory.mkdirs();
А что если не получилось создать директории?

2020-06-17 13:37 UTC, stalker-fc commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +                directory.mkdirs();
@Walingar, будет выброшено `RuntimeException` с уведомлением о невозможности записи в файл (30 строчка).

2020-06-17 13:55 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +                directory.mkdirs();
Т.е. если метод mkdirs вернет false, то будет исполняться 30 строчка?

2020-06-17 14:00 UTC, stalker-fc commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +                directory.mkdirs();
@Walingar, посмотрел документацию. Думал, что в случае ошибки при создании директории, бросается исключение. Оказалось, что такой функционал не реализован. Добавлю проверку на этот случай.

2020-06-20 10:31 UTC, stalker-fc commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +                directory.mkdirs();
@Walingar, fixed

2020-06-25 09:22 UTC, Walingar approved these changes

2020-06-25 09:22 UTC, merged