HW7: Stepanov Sergey
Walingar/java-is-2020 pull request #189
Opened 2020-06-01 17:21 UTC by stalker-fc

2020-06-17 14:46 UTC, Walingar requested changes

2020-06-17 14:46 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +public class StudentDB implements StudentQuery {
Следует вынести общие части методов

2020-06-20 11:20 UTC, stalker-fc commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +public class StudentDB implements StudentQuery {
@Walingar, fixed

2020-06-25 09:26 UTC, Walingar requested changes

2020-06-25 09:26 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +        return students.stream().map(mapper).collect(Collectors.toList());
Общий кусок у этого и следующего метода есть

2020-06-25 09:26 UTC, Walingar commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +        return sortStudentsByKey(students, Comparator.comparingInt(Student::getId));
Общий `Comparator.comparingInt(Student::getId)`

2020-06-26 17:02 UTC, stalker-fc commented on src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
> +        return students.stream().map(mapper).collect(Collectors.toList());
@Walingar, вынес общий Stream, выглядит это просто ужасно

2020-06-27 20:43 UTC, Walingar approved these changes

2020-06-27 20:43 UTC, merged