Task 1 Alexandra Klemesheva
Walingar/java-is-2020 pull request #19
Opened 2020-02-26 16:53 UTC by ITLeopard

2020-03-24 19:38 UTC, Walingar commented
Почитай: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
Порой можно не делать новые коммиты, а заменить старые.

2020-03-24 19:39 UTC, Walingar commented
Удали, пожалуйста, ненужные картинки txt и прочее :)

2020-03-24 19:46 UTC, Walingar requested changes
Хорошо. Нужно исправить недочеты.

2020-03-24 19:46 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderFactory.java
> +        return new ConvolutionProviderImplementation();  // возвращаем объект, в котором реализован интерфейс ConvolutionProvider
Комментарии лучше писать на английском

2020-03-24 19:46 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImplementation.java
> +//                while (m1 <= i + step && m2 >= 0) {
Лучше такие комментарии не оставлять в production коде

2020-03-24 19:46 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImplementation.java
> +                int m1 = -step;
Непонятные названия переменных

2020-03-24 19:46 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImplementation.java
> +        int step = (int) Math.floor(size / 2);
int уже округляет к 0

2020-03-24 19:46 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImplementation.java
> +                        } catch (ArrayIndexOutOfBoundsException e) {
Я говорил на лекции, что лучше так не делать. Нужно обрабатывать такие вещи с помощью `if`

2020-03-24 19:46 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImplementation.java
> +                            green = Math.max(0, green);
А что если захочется сравнивать не с 0, а с 10

2020-03-24 19:46 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImplementation.java
> +                            green += (int) image[i + m1][j + n1].getGreen() * kernelItem;
А что если захочется делать не `image[i + m1][j + n1]`, а `image[i + m1][j + n1 + shiftX]`

2020-03-24 19:46 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImplementation.java
> +                for (m1 = -step, m2 = size - 1; m1 <= i + step && m2 >= 0; m1++, m2--) {
Очень сложно читается такой `if`

2020-03-24 19:46 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImplementation.java
> +                for (m1 = -step, m2 = size - 1; m1 <= i + step && m2 >= 0; m1++, m2--) {
Неговорящие названия переменных, как минимум

2020-03-24 19:46 UTC, Walingar commented on src/main/java/impl/image/ImageConveterImplementation.java
> +                String tempStr = Integer.toBinaryString(image[i][j]);
Следует почитать документацию к `Color` и написать эти методы проще

2020-04-03 16:27 UTC, Walingar commented
Пожалуйста, используй английский язык в коммит сообщениях

2020-04-03 16:34 UTC, Walingar requested changes

2020-04-03 16:34 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImplementation.java
> +    boolean ifInRange(int i, int length) {
`isInRange`

2020-04-03 16:34 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImplementation.java
> +                        } else {
А для чего эта ветка?

2020-04-03 16:34 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImplementation.java
> +                while (imageRow <= i + step && kernelRow >= 0) {
Мне кажется, немного сложновато, что i - это imageRow, и imageRow это imageRow

2020-04-03 16:34 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImplementation.java
> +                        if (ifInRange(i + imageRow, image.length) && ifInRange(j + imageColumn, image[0].length)) {
Два раза image[0].length

2020-04-03 16:34 UTC, Walingar commented on src/main/java/impl/image/ImageConveterImplementation.java
> +        int colorLength = 32;
unused

2020-04-03 16:34 UTC, Walingar commented on src/main/java/impl/image/ImageConveterImplementation.java
> +        int colorLength = 8;
unused

2020-04-03 17:04 UTC, ITLeopard commented on src/main/java/impl/image/ConvolutionProviderImplementation.java
> +                while (imageRow <= i + step && kernelRow >= 0) {
Не очень понимаю, что здесь не так... Разные циклы - разные переменные, хотя они и обозначают фактически одно и то же. Если я сделаю их одной переменной, придется уменьшить количество циклов, а это нарушит логику и программа перестанет работать

2020-04-03 17:10 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImplementation.java
> +                while (imageRow <= i + step && kernelRow >= 0) {
В таком коде легко запутаться. Нужно или обозначить i по-другому, или написать код так, чтобы не было разногласий (например, сделать это через shiftRow, shiftColumn). 
Обычно, если не знаешь, как можно нормально назвать переменную, значит код написан странно

2020-06-20 08:39 UTC, Walingar approved these changes

2020-06-20 08:39 UTC, merged