HW8: Vereshok Elena
Walingar/java-is-2020 pull request #200
Opened 2020-06-17 17:35 UTC by GranPecador

2020-06-25 10:04 UTC, Walingar requested changes

2020-06-25 10:04 UTC, Walingar commented on src/main/java/impl/matrix/Multiplier.java
> +    int start, end;
Рекомендовано писать по 1 филду/переменной на одной строке

2020-06-25 10:04 UTC, Walingar commented on src/main/java/impl/matrix/Multiplier.java
> +    int start, end;
Точно филды должны быть package-private? А если кто-то поменяет result из вне?

2020-06-25 10:04 UTC, Walingar commented on src/main/java/impl/matrix/Multiplier.java
> +    public Multiplier(int start, int end, int bColumns, int bRows, double[][] a, double[][] b, double[][] result) {
Точно ли нужны аргументы int bColumns и int bRows? Они же вычисляются из b?

2020-06-25 10:04 UTC, Walingar commented on src/main/java/impl/matrix/Multiplier.java
> +        for (int i = start; i < end; i++) {
Получается, если матрица `a` является строкой, то будет использовать только 1 поток

2020-06-25 10:04 UTC, Walingar commented on src/main/java/impl/matrix/ParallelMultiplierImpl.java
> +        int nBar = aRows / maxThreads;
nBar?

2020-06-25 10:04 UTC, Walingar commented on src/main/java/impl/matrix/ParallelMultiplierImpl.java
> +            try {
Получается, что у тебя в одно время работает только один поток. Нет никакого параллелизма

2020-06-25 10:04 UTC, Walingar commented on src/main/java/impl/matrix/ParallelMultiplierImpl.java
> +            int end = (threadCurrent != maxThreads - 1) ? (threadCurrent + 1) * nBar : (threadCurrent + 1) * nBar + residue;
threadCurrent + 1

2020-06-27 20:47 UTC, Walingar requested changes

2020-06-27 20:47 UTC, Walingar commented on src/main/java/impl/matrix/Multiplier.java
> +
Очень много пустых строк

2020-06-27 21:22 UTC, GranPecador commented on src/main/java/impl/matrix/Multiplier.java
> +
упс

2020-06-30 22:05 UTC, Walingar approved these changes

2020-06-30 22:05 UTC, merged