HW9: Semenkin Eduard
Walingar/java-is-2020 pull request #230
Opened 2020-06-21 20:10 UTC by Eduard585

2020-06-25 11:46 UTC, Walingar requested changes

2020-06-25 11:46 UTC, Walingar commented on src/main/java/impl/network/FollowersStatsImpl.java
> +    private CompletableFuture<Integer> count(int id, int depth, Predicate<UserInfo> predicate, ConcurrentHashMap<Integer, Boolean> visitMap) {
Следует использовать интерфейс, а не реализацию `ConcurrentHashMap`

2020-06-25 11:46 UTC, Walingar commented on src/main/java/impl/network/FollowersStatsImpl.java
> +        if (depth == 0) return userCountFuture;
Следует всегда использовать { }. По правилам я должен закрыть PR. но ладно уж. Исправляй

2020-06-25 11:46 UTC, Walingar commented on src/main/java/impl/network/FollowersStatsImpl.java
> +                                follower -> {
Можно на предыдущую строчку follower -> пренести

2020-06-25 11:46 UTC, Walingar commented on src/main/java/impl/network/FollowersStatsImpl.java
> +                        (userInfo) -> predicate.test(userInfo) ? 1 : 0
Тут явно лишний перенос на новую строку

2020-06-25 11:46 UTC, Walingar commented on src/main/java/impl/network/FollowersStatsImpl.java
> +                        .reduce(CompletableFuture.completedFuture(0), (subtotalFuture, additionFuture) -> subtotalFuture.thenCombine(additionFuture, Integer::sum))
А вот тут наоборот лучше сделать перенос

2020-07-03 14:34 UTC, Walingar requested changes

2020-07-03 14:34 UTC, Walingar commented on src/main/java/impl/network/FollowersStatsImpl.java
> +    private CompletableFuture<Integer> count(int id, int depth, Predicate<UserInfo> predicate, ConcurrentMap<Integer, Boolean> visitMap) {
Map<Integer, Boolean> == Set<Integer>

2020-07-05 19:01 UTC, Walingar requested changes

2020-07-05 19:01 UTC, Walingar commented on src/main/java/impl/network/FollowersStatsImpl.java
> +                new HashSet<>() {{
HashSet не является потоко-безопасным классом

2020-07-06 10:07 UTC, Walingar requested changes

2020-07-06 10:07 UTC, Walingar commented on src/main/java/impl/network/FollowersStatsImpl.java
> +                new CopyOnWriteArraySet<>() {{
В чем причина использования данной реализации? Ведь в этот Set элементы часто добавляются

2020-07-06 11:10 UTC, Eduard585 commented on src/main/java/impl/network/FollowersStatsImpl.java
> +                new CopyOnWriteArraySet<>() {{
Я использовал thread safe реализацию. У нас есть 3 thread safe set'a. CopyOnWriteArraySet,synchronizedSet и ConcurrentSkipListSet. Первый долгий O(n), второй оборачивает методы в synchronized и по сути, блокируется, а третий является многопоточной реализацией SortedSet, но я затруднясь сказать в чем конкретно его особенность. Кажется, что нужно использовать его

2020-07-06 11:14 UTC, Walingar commented on src/main/java/impl/network/FollowersStatsImpl.java
> +                new CopyOnWriteArraySet<>() {{
Почему ты считаешь, что реализаций всего 3? Все операции в SkipListSet работают за логарифм — тоже не оч хорошо

2020-07-06 11:25 UTC, Eduard585 commented on src/main/java/impl/network/FollowersStatsImpl.java
> +                new CopyOnWriteArraySet<>() {{
А, ну можно еще получить Set из ConcurrentHashMap, который вроде имеет полный паралеллизм на чтение и O(1) Инфу я взял отсюда https://stackoverflow.com/questions/6720396/different-types-of-thread-safe-sets-in-java

2020-07-06 11:27 UTC, Walingar commented on src/main/java/impl/network/FollowersStatsImpl.java
> +                new CopyOnWriteArraySet<>() {{
Именно его и хорошо здесь использовать :)

2020-07-06 11:38 UTC, Eduard585 commented on src/main/java/impl/network/FollowersStatsImpl.java
> +                new CopyOnWriteArraySet<>() {{
Теперь вроде то что нужно

2020-07-06 11:48 UTC, Walingar approved these changes

2020-07-06 11:48 UTC, merged