HW8: Dmitrii Kuklin
Walingar/java-is-2020 pull request #231
Opened 2020-06-21 20:33 UTC by Diamindes

2020-06-25 10:32 UTC, Walingar requested changes

2020-06-25 10:32 UTC, Walingar commented on src/main/java/api/matrix/Executor.java
> +  private List<Worker> workers;
final

2020-06-25 10:32 UTC, Walingar commented on src/main/java/api/matrix/Executor.java
> +public class Executor {
Executor -- плохое название. Непонятно, что он делает, должен делать

2020-06-25 10:32 UTC, Walingar commented on src/main/java/api/matrix/Executor.java
> +    private double[][] secondMatrix;
final

2020-06-25 10:32 UTC, Walingar commented on src/main/java/api/matrix/Executor.java
> +    public void run() {
Получается не очень приятная ситуация, что нужно обязательно сделать setTask прежде чем запускать задачу...

2020-06-30 15:22 UTC, Diamindes commented on src/main/java/api/matrix/Executor.java
> +  private List<Worker> workers;
done

2020-06-30 15:23 UTC, Diamindes commented on src/main/java/api/matrix/Executor.java
> +public class Executor {
Переименовал в ParallelMultiplierExecutor, не верен что стало понятнее, но хотя бы рядом лежит и понятно к кому он относится

2020-06-30 15:23 UTC, Diamindes commented on src/main/java/api/matrix/Executor.java
> +    private double[][] secondMatrix;
done

2020-06-30 15:26 UTC, Diamindes commented on src/main/java/api/matrix/Executor.java
> +    public void run() {
Если использовать Worker для выполнения другой задачи или напрямую, то плохо, но в данном случае это архитектурная задумка)

Worker закрыт и вызывает его только Executor, который не выпускает его наружу и сам сетает задания перед запуском.

2020-06-30 22:10 UTC, Walingar approved these changes

2020-06-30 22:10 UTC, merged