[HW_9] add FollowersStats implementation
Walingar/java-is-2020 pull request #232
Opened 2020-06-21 20:57 UTC by Diamindes

2020-06-25 11:50 UTC, Walingar requested changes

2020-06-25 11:50 UTC, Walingar commented on src/main/java/impl/network/FollowersStatsImpl.java
> +      Predicate<UserInfo> predicate, ConcurrentSkipListSet<Integer> visited) {
Следует использовать интерфейс, а не реализацию `ConcurrentSkipListSet`

2020-06-25 11:50 UTC, Walingar commented on src/main/java/impl/network/FollowersStatsImpl.java
> +    return followersCountBy(id, depth, predicate, new ConcurrentSkipListSet<>() {{ add(id); }});
Почему выбор пал на ConcurrentSkipListSet, а не HashSet? ConcurrentHashSet?

2020-06-30 15:26 UTC, Diamindes commented on src/main/java/impl/network/FollowersStatsImpl.java
> +      Predicate<UserInfo> predicate, ConcurrentSkipListSet<Integer> visited) {
done

2020-06-30 15:29 UTC, Diamindes commented on src/main/java/impl/network/FollowersStatsImpl.java
> +    return followersCountBy(id, depth, predicate, new ConcurrentSkipListSet<>() {{ add(id); }});
ConcurrentSkipListSet просто удобнее для инициализации. Он даёт то же самое что и ConcurrentHashSet. Только его не нужно доставать из мапы ConcurrentHashMap, т.к ConcurrentHashSet напрямую не создать

ConcurrentHashMap - не удобно тащить мапу внутрь.
HashSet - тесты на нём проходят, но что-то я в нём не уверен)

2020-06-30 22:14 UTC, Walingar commented on src/main/java/impl/network/FollowersStatsImpl.java
> +    return followersCountBy(id, depth, predicate, new ConcurrentSkipListSet<>() {{ add(id); }});
Да, вот только `ConcurrentSkipListSet` имеет сложность операций O(log(n)), в сравнении с константами у ConcurrentHashMap

2020-06-30 22:16 UTC, Walingar commented on src/main/java/impl/network/FollowersStatsImpl.java
> +    return followersCountBy(id, depth, predicate, new ConcurrentSkipListSet<>() {{ add(id); }});
А вот то, что не уверен в HashSet -- это правильно :)

2020-06-30 22:17 UTC, Walingar requested changes
Заиспользуй ConcurrentHashMap

2020-07-01 13:46 UTC, Diamindes commented on src/main/java/impl/network/FollowersStatsImpl.java
> +    return followersCountBy(id, depth, predicate, new ConcurrentSkipListSet<>() {{ add(id); }});
ок, переделал под ConcurrentHashMap

2020-07-01 20:57 UTC, Walingar approved these changes

2020-07-01 20:57 UTC, merged