HW_2
Walingar/java-is-2020 pull request #32
Opened 2020-02-28 01:02 UTC by Diamindes

2020-03-31 17:57 UTC, Walingar requested changes

2020-03-31 17:57 UTC, Walingar commented on src/main/java/api/expression/impl/ExpressionParserImpl.java
> +    return expression
Прикольно) Но, так не пойдет)

2020-03-31 17:57 UTC, Walingar commented on src/main/java/api/expression/impl/ExpressionParserImpl.java
> +    return expression
Проблема в том, что мы тут потребляем в 2 раза больше памяти на пустом месте + если мы захотим перевести наше решение на стримы, то ничего не получится.
Надо все делать в процессе прохода по строчке

2020-03-31 17:57 UTC, Walingar commented on src/main/java/api/expression/impl/ExpressionParserImpl.java
> +      throw new ParseException(exception.getMessage(), exception);
Это круто!

2020-06-30 14:59 UTC, Diamindes commented on src/main/java/api/expression/impl/ExpressionParserImpl.java
> +    return expression
переделал

2020-06-30 14:59 UTC, Diamindes commented on src/main/java/api/expression/impl/ExpressionParserImpl.java
> +    return expression
переделал

2020-06-30 19:33 UTC, Walingar approved these changes

2020-06-30 19:34 UTC, merged