Huan nguyen task 2
Walingar/java-is-2020 pull request #38
Opened 2020-03-04 22:09 UTC by vodanhst

2020-03-31 18:53 UTC, Walingar requested changes

2020-03-31 18:53 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserFactory.java
> +        ExpressionParser expressionParser = new ExpressionParser(){
codestyle

2020-03-31 18:53 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserFactory.java
> +        ExpressionParser expressionParser = new ExpressionParser(){
В соблюдении codestyle поможет action Reformat code в IDEA

2020-03-31 18:53 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserFactory.java
> +                String[] decima = expression.split("[\\t\\n ]+");
Почитай https://en.wikipedia.org/wiki/Whitespace_character

2020-03-31 18:53 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserFactory.java
> +                String[] decima = expression.split("[\\t\\n ]+");
Не очень хорошо использовать здесь split, т.к. это решение не масштабируется, его сложно использовать вместе с потоками в дальнейшем

2020-03-31 18:53 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserFactory.java
> +                for (int i = 0; i<decima.length; i++){
codestyle

2020-03-31 18:53 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserFactory.java
> +                String[] decima = expression.split("[\\t\\n ]+");
Что значит decima?

2020-03-31 18:53 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserFactory.java
> +                int k = 1;
что такое k?

2020-03-31 18:53 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserFactory.java
> +                        if (Math.abs(temp) >= Math.abs(Integer.MAX_VALUE - sum)){
попробуй поискать, как лучше проверить на переполнение

2020-03-31 18:53 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserFactory.java
> +                        sum = sum + k*temp;
А что если переполнение будет при сумме?

2020-03-31 18:53 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserFactory.java
> +        ExpressionParser expressionParser = new ExpressionParser(){
Лучше не использовать здесь анонимные классы. Лучше создать отдельный класс-имплементацию

2020-06-27 20:30 UTC, Walingar requested changes
Замечания не были исправлены

2020-06-27 20:30 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParser.java
> +                if (expressionParts[i].equals("+")) {
Выдели общую переменную. А лучше использовать for для Itterable

2020-06-27 20:30 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserFactory.java
> +        ExpressionParser expressionParser = new ExpressionParser(){
Не исправлено замечание об анонимных классах

2020-06-27 20:30 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParser.java
> +        String[] expressionParts = expression.split("[\\t\\n ]+");
Не исправлено замечание по поводу split

2020-06-28 14:10 UTC, vodanhst commented on src/main/java/impl/expression/ExpressionParser.java
> +        String[] expressionParts = expression.split("[\\t\\n ]+");
На что заменить split я не знаю. В Хорстманне не написано, в интернете тоже

2020-06-30 06:21 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParser.java
> +        String[] expressionParts = expression.split("[\\t\\n ]+");
https://en.m.wikipedia.org/wiki/Recursive_descent_parser

2020-06-30 19:34 UTC, Walingar requested changes
Замечания не исправлены

2020-06-30 19:35 UTC, closed without merging