HW2: Klemesheva Alexandra
Walingar/java-is-2020 pull request #39
Opened 2020-03-07 16:20 UTC by ITLeopard

2020-03-31 18:54 UTC, Walingar commented
Почитай о том, как изменять историю репозитория  https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

2020-03-31 19:06 UTC, Walingar requested changes

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +        //замена всех пробельных символов на пробелы
После // должен быть пробел

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +        //замена всех пробельных символов на пробелы
Комментарии следует все же писать на английском

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +        StringBuffer expBuf = new StringBuffer(expression);
StringBuffer не следует использовать. Нужно использовать StringBuilder. Почитай документацию к StringBuffer, там сказано

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +        } catch (Exception e) {
Зачем тут ловить Exception?

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +            expression = expression.replaceAll("\\s", " ");
Лучше все же не делать такую замену, т.к. такое решение просто так кушает в 2 раза больше памяти, но более важно, что такое решение не масштабируется, т.е. его нельзя перевести на потоки

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +        //замена всех пробельных символов на пробелы
Вместо таких комметариев лучше выделять методы с соответствующими названиями :)

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +        //Обособление знаков + и - пробелами
Зачем такое обособление?

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +        String[] words = String.valueOf(expBuf).split(" ");
Можно ли тут обойтись без split?

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +            if (word.equals("")) {
isEmpty

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +            } else if (result.equals("")) {
isEmpty

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +                continue;
Не очень хорошо писать такой continue, т.к. все равно после этого ничего не испольняется. Но и пустой if не хорошо писать. Лучше сделать логику наоброт

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +                result += word;
Не хорошо делать += к строке, это работает долго, т.к. строка неизменяемая структура

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +                result = word;
Сложноватая логика с result строкой

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +                } catch (Exception e) {
Почему ловим тут любой Exception?

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +                if (Math.abs(Integer.MAX_VALUE - resultOld) < wordInt) {
Попробуй найти более простой способ проверки на переполнение

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +                int resultOld = 0;
Код в верхней ветке выглядит очень похожим на этот

2020-03-31 19:06 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +        if (empty) {
Может быть проверить это в начале?

2020-04-02 15:43 UTC, ITLeopard commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +        //Обособление знаков + и - пробелами
Для реализации алгоритма парсинга - чтобы можно было разделить всю строку на отдельные лексемы и работать с каждой из них

2020-06-19 15:43 UTC, ITLeopard commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +                            (int) Math.pow(10, numberDigits)), curOperand);
Тут я не уверена, как правильно разбить слишком длинную строку на несколько. Если я не угадала, не закрывай пулл реквест, пожалуйста, а объясни как правильно это делать...

2020-06-20 08:42 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImplementation.java
> +                            (int) Math.pow(10, numberDigits)), curOperand);
Тут вариантов много, одиночного решения для джавы здесь нет. Но я обычно использую подход, как в котлине: https://kotlinlang.org/docs/reference/coding-conventions.html#method-call-formatting

2020-06-20 08:42 UTC, Walingar approved these changes

2020-06-20 08:42 UTC, merged