HW2: Ivanov Danil
Walingar/java-is-2020 pull request #41
Opened 2020-03-10 19:26 UTC by NeHo4y

2020-03-31 19:24 UTC, Walingar requested changes

2020-03-31 19:24 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +        if (currentNumber.length() != 0){
codestyle

2020-03-31 19:24 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +    StringBuilder currentNumber;
private final

2020-03-31 19:24 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +    char sign;
private

2020-03-31 19:24 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +        sign = '+';
sign не используется

2020-03-31 19:24 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +    private int calculate(int a, int b) throws ArithmeticException {
ArithmeticException - это unchecked exception его можно не указывать

2020-03-31 19:24 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                currentNumber.append(processed_char);
Может так получится, что вся строчка - это цифры и мы скушаем в 2 раза больше памяти, можно этого как-то избежать?

2020-04-15 15:03 UTC, NeHo4y commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                currentNumber.append(processed_char);
Сделал, можно сразу попробовать parseInt, если не получилось уже считать посимвольно

2020-04-15 17:54 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                currentNumber.append(processed_char);
А если строка такого вида? `5-2342343242343....2343` Очень длинное число

2020-04-15 17:55 UTC, Walingar requested changes

2020-04-15 17:55 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                        currentNumber.append(processed_char);
Все равно мы можем здесь проиграть по памяти, сохранив очень длинное число

2020-04-15 17:55 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                        if (currentNumber.length() != 0) {
copy-paste, ниже точно такое же выражение

2020-06-20 08:43 UTC, Walingar approved these changes

2020-06-20 08:43 UTC, merged