HW2: Shayakhmetov Danil
Walingar/java-is-2020 pull request #44
Opened 2020-03-11 21:02 UTC by DanilShayakhmetov

2020-03-31 19:36 UTC, Walingar commented
Почитай о том, как изменять историю репозитория https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

2020-03-31 19:37 UTC, Walingar commented
Тут лишнее первое дз

2020-03-31 19:44 UTC, Walingar requested changes

2020-03-31 19:44 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +            operators.remove(operators.size()-1);
codestyle

2020-03-31 19:44 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +        expression = expression.replaceAll("\\s+", "");
Не очень хорошо так делать, т.к. наше решение получается не масштабируемым, оно не может просто так использоваться со стримами. Мы же все равно проходим по всей строчке, можем там и проверять на пробельный символ

2020-03-31 19:44 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +        expression += '+';
Зачем это действие?

2020-03-31 19:44 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +            if (result >= Integer.MAX_VALUE) {
Это решение не будет работать, если будет передана строка `MAX_VALUE / 2 + MAX_VALUE / 2 + 2`

2020-03-31 19:44 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                throw new ArithmeticException();
Сообщение об ошибке?

2020-03-31 19:44 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +        if (expElements[0] == '-') {
Точно ли нужна доп логика на первый символ?

2020-03-31 19:44 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +        ExpressionParserImpl calculator = new ExpressionParserImpl();
Зачем здесь создавать новый объект?

2020-03-31 19:44 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                buffer += element;
Прибавление к строке работает долго, т.к. строка immutable структура

2020-03-31 19:44 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +        ArrayList<String> operators = new ArrayList<>();
Может быть можно на ходу вычислять результат без сохранения?

2020-06-30 19:41 UTC, Walingar requested changes

2020-06-30 19:41 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                if (number.toString().equals("")) {
Некрасивый костыль

2020-06-30 19:41 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +            } else if (java.lang.Character.isWhitespace(character)) {
java.lang импортируется по умолчанию

2020-06-30 19:41 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                continue;
Нехорошо делать continue как последнее действие в цикле

2020-06-30 19:41 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                if (number.toString().equals("")) {
Как минимум, лучше написать number.length() == 0

2020-06-30 19:41 UTC, closed without merging

2020-07-01 01:27 UTC, DanilShayakhmetov commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                continue;
А если к строке в начале trim применить то получается можно так оставить?