Task 2
Walingar/java-is-2020 pull request #46
Opened 2020-03-12 06:35 UTC by Eduard585

Please dont mark it as deadline, just forgot to pull request. Did it at sunday 8 march)

2020-03-31 20:03 UTC, Walingar commented
Тут лишняя вторая домашка, посмотри, как можно изменить историю тут https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

2020-03-31 20:11 UTC, Walingar requested changes

2020-03-31 20:11 UTC, Walingar commented on src/main/java/impl/expression/Calculator.java
> +import java.lang.annotation.AnnotationTypeMismatchException;
лишние импорты

2020-03-31 20:11 UTC, Walingar commented on src/main/java/impl/expression/Calculator.java
> +            if (Character.isSpaceChar(curChar) || curChar == '\n' || curChar == '\t') {
Почти попал в метод) isWhitespaceChar :)

2020-03-31 20:11 UTC, Walingar commented on src/main/java/impl/expression/Calculator.java
> +            if (Character.isDigit(curChar) || i == 0) {
А можно без проверки на первый элемент тут справится? Тогда можно будет цикл заменить на `for (char curChar: expression.toCharArray())`

2020-03-31 20:11 UTC, Walingar commented on src/main/java/impl/expression/Calculator.java
> +                continue;
эти continue можно заменить на общие условия с else if

2020-03-31 20:11 UTC, Walingar commented on src/main/java/impl/expression/Calculator.java
> +            if (digit == Integer.MAX_VALUE || digit == Integer.MIN_VALUE) {
Это решение не будет работать, если digit, например, == MAX_VALUE - 1

2020-03-31 20:11 UTC, Walingar commented on src/main/java/impl/expression/Calculator.java
> +            digit = Integer.parseInt(buffer.toString());
digit - это цифра )

2020-03-31 20:11 UTC, Walingar commented on src/main/java/impl/expression/Calculator.java
> +    private int getTempResult(StringBuilder buffer, int result) throws ParseException, ArithmeticException {
Не очень понятное название метода

2020-03-31 20:11 UTC, Walingar commented on src/main/java/impl/expression/Calculator.java
> +    private int getTempResult(StringBuilder buffer, int result) throws ParseException, ArithmeticException {
ArithmeticException - это unchecked exception, его можно не указывать здесь

2020-04-12 22:57 UTC, Eduard585 commented on src/main/java/impl/expression/Calculator.java
> +    private int getTempResult(StringBuilder buffer, int result) throws ParseException, ArithmeticException {
Получить временные результаты) Почему непонятно

2020-04-12 23:02 UTC, Eduard585 commented on src/main/java/impl/expression/Calculator.java
> +                continue;
Зачем так делать если когда мы попадаем в один из if'ов то нам нужно приступить к следующей итерации

2020-04-18 17:40 UTC, Walingar commented on src/main/java/impl/expression/Calculator.java
> +                continue;
У тебя получается код вида:
```
if (expr1) {
  ...
  continue;
}
if (expr2) {
  ...
  continue;
}
if (expr3) {
  ...
}
``` 
Кажется, что лучше этот код заменить на:
```
if (expr1) {
  ...
} else if (expr2) {
  ...
} else if (expr3) {
  ...
} else {
  illegal state?
}
```

2020-04-18 17:42 UTC, Walingar commented on src/main/java/impl/expression/Calculator.java
> +    private int getTempResult(StringBuilder buffer, int result) throws ParseException, ArithmeticException {
Какой временный? Результат чего?

2020-04-18 17:43 UTC, Walingar commented
Попробуй все же поправить ревью, чтобы в реквесте остались коммиты только текущего задания

2020-05-18 18:44 UTC, Walingar commented
> This branch cannot be rebased due to conflicts
Поправь, пожалуйста, историю, чтобы были только коммиты из ветки eduard-semenkin-task-2 + коммиты твоего решения

2020-05-19 19:47 UTC, closed without merging