HW3: Klemesheva Alexandra
Walingar/java-is-2020 pull request #53
Opened 2020-03-24 09:46 UTC by ITLeopard

2020-04-01 09:53 UTC, Walingar commented
Такая же проблема, как и со второй домашкой, просочились коммиты из первой домашки

2020-04-01 09:59 UTC, ITLeopard commented
"Такая же проблема, как и со второй домашкой, просочились коммиты из первой домашки"
Это очень важно? Или можно так оставить?
Первую домашку я делала в ветке master, поэтому эти коммиты и тянутся на все домашки.

2020-04-01 10:00 UTC, Walingar commented
Попробуй все же изменить историю и оставить только нужные коммиты

2020-04-01 10:01 UTC, Walingar requested changes

2020-04-01 10:01 UTC, Walingar commented on src/main/java/api/weather/YearTemperatureStats.java
> +//    public void print();
Такое лучше удалять)

2020-04-01 10:01 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoImpl.java
> +    public void setTemperature(int temperature) {
unused method

2020-04-01 10:01 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoImpl.java
> +    private Month month;
final

2020-04-01 10:01 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsParserImpl.java
> +            int day = Integer.parseInt(str.substring(0, str.indexOf('.')));
много раз делаешь indexOf('.')

2020-04-01 10:01 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +//    public void print() {
Этот комментарий тоже не нужен)

2020-04-01 10:01 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private Collection<DayTemperatureInfo> _dayTempInfo = new ArrayList<>();
В джаве не любят использовать нижние подчеркивания. Раньше, когда не было поддержки IDE, использовали префикс my, чтобы отличать филд и аргумент метода

2020-04-01 10:01 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private Collection<DayTemperatureInfo> _dayTempInfo = new ArrayList<>();
final

2020-04-01 10:01 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    public Double getAverageTemperature(Month month) {
Ты на каждый запрос пересчитываешь среднее

2020-04-01 10:01 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        Map<Month, Integer> result = new HashMap<>();
Аналогично, ты на каждый запрос пересчитываешь максимум, даже если новые данные не пришли

2020-06-20 08:58 UTC, Walingar requested changes

2020-06-20 08:58 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (!newData) {
Получается, если пришла информация об одном дне, ты будешь пересчитывать среднее. Можно сделать так, чтобы всегда считалось за константное время

2020-06-20 08:58 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (!newData) {
Подсказка: обновляй статистику в updateStats за константное время

2020-06-20 08:58 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    Map<Month, Integer> temperatureMax;
Получается, если мы захотим иметь статистику о минимальной температуре, медианной температуре и прочем, то нужно будет создавать много словарей? Плохо. Нужно выделить класс, который будет содержать и уметь сам обновлять информацию о конкретном месяце

2020-06-20 08:58 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    boolean newData = true;
А что если какой-то внешний злой человек будет делать тут false всегда. Кажется, будет грустно. Твой контракт будет нарушен. Что обычно используется, чтобы контракт, а именно инвариант, не нарушался?

2020-06-20 09:05 UTC, ITLeopard commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (!newData) {
Объясни, пожалуйста, что означает "за константное время"?

2020-06-20 09:07 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (!newData) {
Я не могу объяснить это понятие за быстро, его должны были рассказывать в бакалавриате в курсе "Алгоритмы и структуры данных"

2020-06-20 09:09 UTC, ITLeopard commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (!newData) {
У меня не было такого курса в бакалавриате. И в списке вопросов к экзамену для поступления этого не было, на сколько я помню (иначе бы я вряд ли решилась сюда пойти).

2020-06-20 09:11 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (!newData) {
Если список вопросов будет покрывать все темы, которые должен знать студент, то экзамен продлится несколько дней.

2020-06-20 09:14 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (!newData) {
Хорошо, я попробую объяснить, что я имею в виду для данного задания. Сейчас ты пересчитываешь среднюю, максимальную температуры каждый раз (не считая newData, которая на самом деле ни на что не влияет). А можно при каждом update stats делать такое: maxMonthTemperature = max(maxMonthTemperature, dayInfo.getTemperature()); И аналогично можно обновлять среднюю температура, затрачивая одну "операцию" а не проходить по всем данным, чтобы что-то посчитать

2020-06-20 09:15 UTC, ITLeopard commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (!newData) {
Это не остановило экзаменаторов в магистратуре Jetbrains - у них был сложный экзамен с множеством вопросов из разных сфер математики и программирования. Значит, такой экзамен провести возможно.

2020-06-20 09:17 UTC, ITLeopard commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (!newData) {
Если в списке вопросов к экзамену присутствуют лишь некоторые темы, знание которых необходимо для обучения, то как выбирать программу, соответствующую моему уровню знаний?

2020-06-20 09:19 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (!newData) {
Почти каждая программа магистратуры имеет перед собой бакалаврскую. Например, у вас направление 09.04.02. Есть бакалаврская программа, которая имеет номер 09.03.02. Я считаю, что все предметы, которые были в этой программе должны быть известны хотя бы в минимальной степени

2020-06-20 09:20 UTC, ITLeopard commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (!newData) {
Спасибо, теперь я поняла что нужно сделать.

2020-06-20 09:40 UTC, ITLeopard commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (!newData) {
Извини, у меня не сразу приходят твои ответы.
Спасибо, что объяснил, я правда не понимала, что ты от меня хочешь :)

Но насчет "Я считаю, что все предметы, которые были в этой программе должны быть известны хотя бы в минимальной степени" все-таки скажу - я как раз и шла в магистратуру сюда, в ИТМО, чтобы восполнить пробелы в образовании. Хоть я и взяла от своего прошлого университета максимум, все знания, которые мне давали - их все равно недостаточно.
Каждый университет одну и ту же программу составляет на свой лад - морской вуз в основном учит информационным технологиям в транспортной сфере, творческий - инструментам, необходимым дизайнерам. Я даже боюсь представить, что происходит в лесопилке :) Плюс, не зря некоторые вузы котируются, а некоторые - нет. А в магистратуру можно поступить с дипломом любого вуза. 

Этот комментарий не требует ответа, я просто хотела показать тебе ситуацию с моей стороны. Я не просто так допытываюсь до каждой запятой, спрашиваю каждую мелочь. Я просто хочу научиться круто программировать.

2020-06-20 19:55 UTC, Walingar approved these changes

2020-06-20 19:55 UTC, Walingar commented on src/main/java/impl/weather/MonthInfo.java
> +            temperatureAverage = temperature + 0.0;
0.0 не нужно. Можно просто скастовать к double

2020-06-20 19:55 UTC, merged