HW3 : Vereshok Elena
Walingar/java-is-2020 pull request #55
Opened 2020-03-24 23:02 UTC by GranPecador

2020-04-03 17:08 UTC, Walingar requested changes

2020-04-03 17:08 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsFactory.java
> +        var yearTemperatureStats= new YearTemperatureStats(){
codestyle

2020-04-03 17:08 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsFactory.java
> +        List<DayTemperatureInfo> tempList = new ArrayList();
Нужно писать ArrayList<>(). Не нужно использовать raw types, я расскажу о них на лекции по дженерикам

2020-04-03 17:08 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsFactory.java
> +        var yearTemperatureStats= new YearTemperatureStats(){
Не хорошо здесь делать такой большой анонимный класс. Лучше выделить это в отдельный класс-имплементацию

2020-04-03 17:08 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsFactory.java
> +        List<DayTemperatureInfo> tempList = new ArrayList();
Почему не сделать это полем класса ниже?

2020-04-03 17:08 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsFactory.java
> +                AtomicInteger tempSum = new AtomicInteger();
Зачем атомарность?

2020-04-03 17:08 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsFactory.java
> +                return tempSum.doubleValue()/count.doubleValue();
Получается, ты на каждый вызов getAverageTemperature пересчитываешь среднюю температуру, даже если ничего не изменилось

2020-04-03 17:08 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsFactory.java
> +                return maxTemp;
Аналогично, ты пересчитываешь значение максимума каждый раз, даже если ничего не изменилось

2020-04-03 17:08 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsFactory.java
> +                        return temp;
Ты получаешь результат здесь за линейное время, нужно за константное

2020-04-03 17:08 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsFactory.java
>  public class YearTemperatureStatsFactory {
Много ошибок в кодстайле

2020-04-03 17:08 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsFactory.java
> +                Comparator<DayTemperatureInfo> comparator = (o1, o2) -> o1.getTemperature()-o2.getTemperature(); //Comparator.comparing(obj -> obj.getTemperature());
После // лучше делать пробел

2020-04-03 17:08 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsParserFactory.java
> +class DayTemperatureInfoImpl implements DayTemperatureInfo {
Один класс на файл

2020-04-03 17:08 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsParserFactory.java
> +        YearTemperatureStatsParser parser = new YearTemperatureStatsParser() {
И снова тут анонимный класс, зачем?

2020-04-03 17:08 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsParserFactory.java
> +                rawData.forEach(raw -> {
Как ты выбираешь между forEach и обычным for?

2020-04-03 17:08 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsParserFactory.java
> +    private int day;
final

2020-04-16 00:16 UTC, GranPecador commented on src/main/java/impl/weather/YearTemperatureStatsFactory.java
> +                return tempSum.doubleValue()/count.doubleValue();
Да, а как я пойму, что ничего не изменилось?)

2020-04-16 00:22 UTC, GranPecador commented on src/main/java/impl/weather/YearTemperatureStatsFactory.java
> +                return maxTemp;
Да) я же не держу в полях количество всего и вся) у меня нет доказательств, что ничего не изменилось) для того, чтобы понять, что ничего не изменилось, я должна держать флаг на этот месяц, что он не изменился никак, или держать максимумы отдельно и при добавлении сравнивать. Не очень поняла, как в это и предыдущем моменте быть уверенной, что ничего не изменилось. Довериться ограниченности нашего функционала, что он у нас работает как журнал, удалять ничего не можем?

2020-04-16 00:26 UTC, GranPecador commented on src/main/java/impl/weather/YearTemperatureStatsParserFactory.java
> +                rawData.forEach(raw -> {
Смотрю forEach, если его нет беру for + настроение) Приму рекомендации)))

2020-04-16 00:28 UTC, GranPecador commented on src/main/java/impl/weather/YearTemperatureStatsFactory.java
> +                        return temp;
Это не намек, что надо другую структуру данных использовать?) Чет не понимаю как из листа за константное время найти)

2020-05-18 19:09 UTC, Walingar requested changes

2020-05-18 19:09 UTC, Walingar commented on src/main/java/impl/weather/MonthInfo.java
> +    private Map<Integer, DayTemperatureInfo> dayTemperatureMap = new HashMap<>();
final

2020-05-18 19:09 UTC, Walingar commented on src/main/java/impl/weather/MonthInfo.java
> +    private int count = 0;
Точно нужен этот count?

2020-05-18 19:09 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private Map<Month, MonthInfo> monthInfoMap = new HashMap<>();
final

2020-05-18 19:09 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (monthInfoMap.get(info.getMonth()) == null) {
Вынести переменную

2020-05-18 19:09 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (monthInfoMap.get(info.getMonth()) == null) {
putIfAbsent

2020-05-18 19:09 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        return monthInfoMap.get(month).getAverage();
Два раза get

2020-05-18 19:09 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        monthInfoMap.entrySet().forEach(temp -> {
Деструктуризацию тут можно сделать, чтобы не использовать этот temp непонятный

2020-05-18 19:09 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        monthInfoMap.entrySet().forEach(temp -> {
И обычно, если ты не знаешь, как назвать переменную, значит что-то в коде не так

2020-05-18 19:09 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +                    .thenComparing((o1, o2) -> o2.getDay() - o1.getDay());   // костыль, так как я не могу контролировать последовательность, иначе оно не совпадает, так как у меня дни не совпадают с
Почему ты не можешь контроллировать последовательность?
Этот костыль надо убрать :)

2020-05-18 19:09 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            List<DayTemperatureInfo> ofMonth = new ArrayList<>(monthInfoMap.get(month).getDayTemperatureMap().values());
Два раза monthInfoMap.get(month)

2020-06-17 09:52 UTC, Walingar requested changes

2020-06-17 09:52 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoImpl.java
> +    final private int day;
modifiers order

2020-06-17 09:52 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            List<DayTemperatureInfo> ofMonth = new ArrayList<>(monthInfoMap.get(month).getDayTemperatureMap().values());
Не исправлено

2020-06-20 13:22 UTC, Walingar approved these changes

2020-06-20 13:22 UTC, merged