HW3: Leonova Elizaveta
Walingar/java-is-2020 pull request #58
Opened 2020-03-26 10:17 UTC by elisaleonova

2020-04-03 17:27 UTC, Walingar requested changes

2020-04-03 17:27 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoImpl.java
> +    private Month month;
final

2020-04-03 17:27 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private HashMap<Month, Double> avTemperature = new HashMap<>();
Получается, что у тебя три мапы хранят какую-то информацию о месяце. Не удобней ли будет вынести это в отдельный класс MonthInfo?

2020-04-03 17:27 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private HashMap<Month, Double> avTemperature = new HashMap<>();
Следует использовать интерфейс, а не реализацию, т.к. ты не используешь специфические для этой реализации методы

2020-04-03 17:27 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +                maxTemperature.put(month, temperature);
И вот все эти обновления тоже можно инкапсулировать красивенько в отдельном классе

2020-04-03 17:27 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private HashMap<Month, Double> avTemperature = new HashMap<>();
final

2020-04-03 17:27 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +import static java.util.Comparator.*;
ты используешь отсюда только comparing

2020-04-03 17:28 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private HashMap<Month, Double> avTemperature = new HashMap<>();
Кстати, обычно до avg сокращают )

2020-04-18 18:07 UTC, Walingar requested changes

2020-04-18 18:07 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        return yearStats.get(month).getAvgTemperature();
Получается два раза делаем get. Почему не использовать monthInfo?

2020-04-18 18:07 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            monthMaxTemperature.put(month, yearStats.get(month).getMaxTemperature());
Мб можно как-то избавить от get тут?

2020-04-18 18:07 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        MonthInfo monthInfo = yearStats.getOrDefault(month, null);
Точно ли нужен getOrDefault(key, null) ?

2020-04-23 12:26 UTC, elisaleonova commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            monthMaxTemperature.put(month, yearStats.get(month).getMaxTemperature());
Не очень поняла, что имеется ввиду, но попыталась изменить подход

2020-05-18 19:11 UTC, Walingar approved these changes

2020-05-18 19:11 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (!yearStats.containsKey(month)) {
putIfAbsent

2020-05-18 19:11 UTC, merged