[HW_3] add raw changes
Walingar/java-is-2020 pull request #65
Opened 2020-03-26 18:49 UTC by Diamindes

2020-04-03 17:51 UTC, Walingar requested changes

2020-04-03 17:51 UTC, Walingar commented on src/main/java/weather/api/impl/DayTemperatureInfoImpl.java
> +  private Month month;
final

2020-04-03 17:51 UTC, Walingar commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +  private Map<Month, List<DayTemperatureInfo>> temperatureInfo = new HashMap<>();
final

2020-04-03 17:51 UTC, Walingar commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +  private Map<Month, List<DayTemperatureInfo>> temperatureInfo = new HashMap<>();
А почему это не в monthStats?

2020-04-03 17:51 UTC, Walingar commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +    if(Objects.isNull(dayTemperatureInfos)){
codestyle

2020-04-03 17:51 UTC, Walingar commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +      dayTemperatureInfos = new ArrayList<>(Collections.nCopies(60, null));
т.е. если добавился один день, то мы сразу под 60 память выделим?

2020-04-03 17:51 UTC, Walingar commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +      return queue.get(d1) - queue.get(d2);
Мб можно обойтись без этого сравнения? Подсказка: есть реализация Map, которая хранит порядок добавления

2020-04-03 17:51 UTC, Walingar commented on src/main/java/weather/api/impl/YearTemperatureStatsParserImpl.java
> +            String[] processingData = dateStr.replace('.', ' ').split(" ");
Мб можем одним сплитом?

2020-06-30 15:00 UTC, Diamindes commented on src/main/java/weather/api/impl/DayTemperatureInfoImpl.java
> +  private Month month;
done

2020-06-30 15:01 UTC, Diamindes commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +  private Map<Month, List<DayTemperatureInfo>> temperatureInfo = new HashMap<>();
done

2020-06-30 15:02 UTC, Diamindes commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +  private Map<Month, List<DayTemperatureInfo>> temperatureInfo = new HashMap<>();
monthStats - собирает статистику по ходу добавления дней.
temperatureInfo - хранит все дни

2020-06-30 15:02 UTC, Diamindes commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +    if(Objects.isNull(dayTemperatureInfos)){
done

2020-06-30 15:07 UTC, Diamindes commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +      dayTemperatureInfos = new ArrayList<>(Collections.nCopies(60, null));
Уже не помню почему 60 поставил, уменьшил до 32.

У нас по сути календарь с чётким кол-во дней, больше 31 дня в месяце скорее всего не будет.
Далее мы начинаем обращаться к массиву по индексу дня, для этого нужно чтобы все 32 индекса были доступны, пусть и заполненный null.

Мы не так уж много тратим, всё таки это Java, она переживёт, но получаем возможность удобно обрабатывать информацию о днях.

2020-06-30 15:09 UTC, Diamindes commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +      return queue.get(d1) - queue.get(d2);
Поискал варианты, но что-то особо не нашёл способа.

Заменил за связный список:
    public int compareEquals(DayTemperatureInfo d1, DayTemperatureInfo d2) {
      return queue.indexOf(d1) - queue.indexOf(d2);
    }

Чуть лучше чем раньше, но почти то же самое.

2020-06-30 15:09 UTC, Diamindes commented on src/main/java/weather/api/impl/YearTemperatureStatsParserImpl.java
> +            String[] processingData = dateStr.replace('.', ' ').split(" ");
done

2020-06-30 21:29 UTC, Walingar requested changes

2020-06-30 21:29 UTC, Walingar commented on src/main/java/weather/api/impl/DayTemperatureInfoImpl.java
> +  private int day;
final

2020-06-30 21:29 UTC, Walingar commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +    private LinkedList<DayTemperatureInfo> queue = new LinkedList<>();
final

2020-06-30 21:29 UTC, Walingar commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +    private LinkedList<DayTemperatureInfo> queue = new LinkedList<>();
Следует использовать интерфейс, а не реализацию

2020-06-30 21:29 UTC, Walingar commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +      dayTemperatureInfos = new ArrayList<>(Collections.nCopies(60, null));
Какой бы не использовался язык, о памяти нужно думать всегда и не потреблять ненужного.

2020-06-30 21:29 UTC, Walingar commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +      return queue.get(d1) - queue.get(d2);
Здесь бы помогла структура данных LinkedHashMap

2020-06-30 21:29 UTC, closed without merging

2020-07-01 13:43 UTC, Diamindes commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +      dayTemperatureInfos = new ArrayList<>(Collections.nCopies(60, null));
ок, переделал на мапу

2020-07-01 13:45 UTC, Diamindes commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +      return queue.get(d1) - queue.get(d2);
Получилось её всунуть правильно:
https://github.com/Walingar/java-is-2020/pull/238/files#diff-75ff3faeb8c8fd78478f248ed0fd802aR31

2020-07-01 13:45 UTC, Diamindes commented on src/main/java/weather/api/impl/DayTemperatureInfoImpl.java
> +  private int day;
done

2020-07-01 13:45 UTC, Diamindes commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +    private LinkedList<DayTemperatureInfo> queue = new LinkedList<>();
done

2020-07-01 13:45 UTC, Diamindes commented on src/main/java/weather/api/impl/YearTemperatureStatsImpl.java
> +    private LinkedList<DayTemperatureInfo> queue = new LinkedList<>();
done