HW: 3 Andrey Korzhov
Walingar/java-is-2020 pull request #67
Opened 2020-03-26 20:08 UTC by Andy1897

add YearTemperatureStatsParserImpl and YearTemperatureStatsImpl

2020-04-03 18:05 UTC, Walingar requested changes

2020-04-03 18:05 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsParserImpl.java
> +    class DayTemperatureInfoImpl implements DayTemperatureInfo {
static

2020-04-03 18:05 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsParserImpl.java
> +        private Month month;
final

2020-04-03 18:05 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private HashMap<Month, Integer> maxTemperature = new HashMap<>();
Нужно использовать интерфейс, а не реализацию, т.к. ты не используешь ничего специфичного для HashMap

2020-04-03 18:05 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private HashMap<Month, Double> avTemperature = new HashMap<>();
Обычно все же average -> avg

2020-04-03 18:05 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private HashMap<Month, Integer> maxTemperature = new HashMap<>();
Получается, что у тебя 3 мапы хранят какую-то конкретную информацию о месяце, а что если захочется добавить минимум, медиану, и т.п.? Создавать еще n мап?

2020-04-03 18:05 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            yearStats.put(month, new LinkedHashMap<>());
Для чего используется LinkedHashMap? Почему не просто HashMap?

2020-04-03 18:05 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        var stat = yearStats.getOrDefault(month, null);
А что если сделать просто get?

2020-05-31 14:56 UTC, Walingar requested changes
Ответьте, пожалуйста, на вопросы

2020-05-31 14:56 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private Map<Month, Double> avgTemperature = new HashMap<>();
А если захочется еще какую-то информацию хранить о месяце? Еще не сколько отображений будете добавлять?

2020-06-07 20:48 UTC, Andy1897 commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            yearStats.put(month, new LinkedHashMap<>());
LinkedHashMap использую потому, что он запоминает порядок в котором значения добавлялись, поэтому когда делаю сортировку, то автоматически при равных температурах, тот день, который был добавлен первее будет идти первее.

2020-06-07 20:50 UTC, Andy1897 commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        var stat = yearStats.getOrDefault(month, null);
Если сделать просто get, то ничего не изменится, вернется нулл в случае отсутствия элемента. Поэтому getOrDefault делать на мой взгляд не обязательно.

2020-06-17 10:01 UTC, Walingar requested changes

2020-06-17 10:01 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private Map<Month, MonthInfo> monthInfo;
final

2020-06-17 10:01 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            sorted.sort(Comparator.comparingInt(DayTemperatureInfo::getTemperature));
Как учитывается порядок добавления дней при равных температурах?

2020-06-17 19:27 UTC, Andy1897 commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            sorted.sort(Comparator.comparingInt(DayTemperatureInfo::getTemperature));
Таки в итоге ответ будет такой:
Temperatures это LinkedHashMap, он сохраняет порядок добавления, и когда происходит `temperatures.forEach((k, v) -> sorted.add(v)) ;` то две одинаковые температуры, что пришли в разные дни, добавляются в правильном порядке. Стандартный sort порядок не меняет.

2020-06-20 08:58 UTC, Walingar approved these changes

2020-06-20 08:59 UTC, merged