HW4: Sukhikh Alexander
Walingar/java-is-2020 pull request #70
Opened 2020-03-29 15:30 UTC by GitCaptain

2020-04-03 18:41 UTC, Walingar requested changes

2020-04-04 23:52 UTC, GitCaptain commented on src/main/java/queue/impl/QueueLinkedImpl.java
> +public class QueueLinkedImpl implements Queue {
?

2020-04-19 14:59 UTC, Walingar commented on src/main/java/queue/impl/QueueLinkedImpl.java
> +public class QueueLinkedImpl implements Queue {
Не следует использовать Raw Types

2020-04-19 15:08 UTC, Walingar requested changes

2020-04-19 15:08 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    private int capacityMultiplier;
final

2020-04-19 15:08 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    private class QueueArrayIterator implements Iterator {
nested классы лучше располагать внизу, после методов

2020-04-19 15:08 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    private void rearrangeQueue(Set<Integer> unused) {
А что это за Set ?

2020-04-19 15:08 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    private void rearrangeQueue(Set<Integer> unused) {
Сюда всегда null передается

2020-04-19 15:08 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    private void rearrangeQueue(Set<Integer> unused) {
И что делает этот метод?

2020-04-19 15:08 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +        System.arraycopy(from, 0, to, 0, min(from.length, to.length));
Лучше использовать `Arrays.copyOf`

2020-04-19 15:08 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    public Object poll() {
А если мы 100500 раз добавим в очередь, а потом 100500 раз удалим из очереди, зачем нам хранить массив на 100500 элементов?

2020-04-19 15:08 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    private class QueueArrayIterator implements Iterator {
Здесь тоже Raw Type

2020-04-19 15:56 UTC, GitCaptain commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    private int capacityMultiplier;
Что сдесь должно быть final? queue? Она же изменяется

2020-04-19 16:52 UTC, GitCaptain commented on src/main/java/queue/impl/QueueArrayImpl.java
> +        System.arraycopy(from, 0, to, 0, min(from.length, to.length));
он тут не подходит, мне удобнее изменять объекты на месте.

2020-04-19 17:17 UTC, GitCaptain commented on src/main/java/queue/impl/QueueArrayImpl.java
> +    private void rearrangeQueue(Set<Integer> unused) {
Сдвигает очередь в начало массива. Тут были остатки от старого кода просто, я их уберу.

2020-04-20 16:54 UTC, Walingar requested changes

2020-04-20 16:54 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +            reallocateMemory(capacity / capacityMultiplier);
copy-paste capacity / capacityMultiplier

2020-04-20 16:54 UTC, Walingar commented on src/main/java/queue/impl/QueueArrayImpl.java
> +        if (size < capacity / capacityMultiplier && capacity % capacityMultiplier == 0) {
Если мы только что уменьшили capacity, добавили элемент, то мы снова увеличим capacity, потом удалим элемент, capacity снова уменьшится. capacity уменьшают обычно, когда элементов capacity / capacityMultiplier ^ 2

2020-05-18 19:21 UTC, Walingar approved these changes

2020-05-18 19:21 UTC, merged