Task4
Walingar/java-is-2020 pull request #72
Opened 2020-03-30 13:21 UTC by ammarali32

2020-04-03 18:52 UTC, Walingar requested changes

2020-04-03 18:52 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueimpl.java
> +public class ArrayQueueimpl implements Queue<Integer> {
codestyle

2020-04-03 18:52 UTC, Walingar commented on src/main/java/queue/impl/Node.java
> +public class Node {
I guess it is a part of LinkedQueueimpl realization

2020-04-03 18:52 UTC, Walingar commented on src/main/java/queue/impl/Node.java
> +    public void addNext(Node x) {
add -> set

2020-04-03 18:52 UTC, Walingar commented on src/main/java/queue/impl/Node.java
> +    private Object value;
final

2020-04-03 18:52 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueimpl.java
> +        Node NEW = new Node(integer, null);
codestyle

2020-04-03 18:52 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueimpl.java
> +public class LinkedQueueimpl implements Queue<Integer> {
You have a lot of common parts with ArrayQueueimpl, please, extract them to the base class

2020-04-19 15:16 UTC, Walingar requested changes

2020-04-19 15:16 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    public Iterator<Integer> iterator() {
It's better to write nested class

2020-04-19 15:16 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        if (size >= 0) System.arraycopy(elements, 0, newElements, 0, size);
Brackets

2020-04-19 15:16 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +import java.util.*;
There Iterator is needed only

2020-04-19 15:16 UTC, Walingar commented on src/main/java/queue/impl/BaseQueue.java
> +        if (c == null)
Brackets

2020-04-19 15:16 UTC, Walingar commented on src/main/java/queue/impl/BaseQueue.java
> +    public boolean addAll(Collection c) {
Override modifier

2020-04-19 15:16 UTC, Walingar commented on src/main/java/queue/impl/BaseQueue.java
> +public abstract class BaseQueue<Integer> extends AbstractCollection<Integer> implements Queue<Integer> {
You can use AbstractQueue here

2020-04-19 15:16 UTC, Walingar commented on src/main/java/queue/impl/BaseQueue.java
> +    public boolean isEmpty() {
It is already implemented in base class

2020-04-19 15:16 UTC, Walingar commented on src/main/java/queue/impl/BaseQueue.java
> +    public boolean addAll(Collection c) {
It is already implemented in the base class

2020-04-19 15:16 UTC, Walingar commented on src/main/java/queue/impl/BaseQueue.java
> +    public void clear() {
It is already implemented in the base class

2020-04-19 15:16 UTC, Walingar commented on src/main/java/queue/impl/BaseQueue.java
> +    public Integer element() {
Override modifier

2020-04-19 15:16 UTC, Walingar commented on src/main/java/queue/impl/BaseQueue.java
> +        if (x != null)
Brackets

2020-04-19 15:16 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    public Integer poll() {
This method should take constant time, but it takes linear instead

2020-05-18 19:32 UTC, Walingar requested changes

2020-05-18 19:32 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +import java.lang.reflect.Field;
redundant import

2020-05-18 19:32 UTC, Walingar commented on src/main/java/queue/impl/BaseQueue.java
> +public abstract class BaseQueue<Integer> extends AbstractQueue<Integer> {
You create a generic parameter with name Integer it is not an Integer type here.
Use `public abstract class BaseQueue extends AbstractQueue<Integer>`

2020-05-18 19:32 UTC, Walingar commented on src/main/java/queue/impl/BaseQueue.java
> +        return this.size;
redundant this

2020-05-18 19:32 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private int IndexCircularArray = 0;
codestyle

2020-05-18 19:32 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private int Cap = 10;
codestyle

2020-05-18 19:32 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private Integer[] elements = new Integer[10];
If you want to change initial capacity you will need to change two places...

2020-05-18 19:32 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        if (size == Cap / 2 && size >= 10) {
Why do you check size here but for extending you check it inside ensureCapacity? It is strange

2020-05-18 19:32 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        if (size == Cap / 2 && size >= 10) {
And one more thing: If you are on the border of capacity changing then you will always extend/shrink size for each add/poll

2020-05-18 19:32 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        if (size == Cap / 2 && size >= 10) {
What if I ask you to increase size in 3 times? You will change each `2` literal?

2020-05-18 19:32 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    private Node Head, last;
cotestyle

2020-05-18 19:32 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    private class LinkedQueueIterator implements Iterator<Integer> {
code-style: nested class should be after methods

2020-05-18 19:32 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        private final Object value;
Why Object? Integer may be?

2020-05-31 14:57 UTC, Walingar commented
this PR couldn't be merged, please, fix it

2020-05-31 15:01 UTC, Walingar requested changes

2020-05-31 15:01 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private void ensureCapacity(int capacity) {
this method is hard to understand, please, rewrite it

2020-06-17 10:11 UTC, Walingar requested changes
code-style issues

2020-06-17 10:12 UTC, Walingar commented
And please, rewrite history. Now it contains conflicts with your branch in main repo.

2020-06-17 11:03 UTC, ammarali32 commented
> And please, rewrite history. Now it contains conflicts with your branch in main repo.

What are the conflicts for me it is written that there are no conflicts and able to merge

2020-06-17 11:05 UTC, ammarali32 commented
> code-style issues

I just found two blank lines are there any other issues?

2020-06-20 09:58 UTC, Walingar approved these changes

2020-06-20 09:58 UTC, merged