HW4 :  Vereshkok Elena
Walingar/java-is-2020 pull request #78
Opened 2020-04-08 13:15 UTC by GranPecador

2020-04-19 15:43 UTC, Walingar requested changes

2020-04-19 15:43 UTC, Walingar commented on src/main/java/queue/impl/Link.java
> +public class Link {
Это часть имплементации LinkedQueue, создай там nested class просто

2020-04-19 15:43 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueFactory.java
> +        var queueInts = new AbstractQueue<Integer>() {
Мне в каждом ревью нужно говорить, что не нужно использовать анонимные классы в таком контексте ? ((( 
Не буду внутрь смотреть, пока не выделишь отдельные классы.

2020-04-19 18:26 UTC, GranPecador commented on src/main/java/queue/impl/ArrayQueueFactory.java
> +        var queueInts = new AbstractQueue<Integer>() {
Теперь поняла:)

2020-05-19 07:38 UTC, Walingar requested changes

2020-05-19 07:38 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    int sizeMas = 0;
Что такое Mas ?

2020-05-19 07:38 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +            if (mas.length - mas.length/3 >= --sizeMas) {
code-style

2020-05-19 07:38 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +                System.arraycopy(mas, 1, mas, 0, sizeMas);
Получается, у тебя удаление элемента работает за линейное время

2020-05-19 07:38 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        if (sizeMas > 0) {
копи паста с poll

2020-05-19 07:38 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        Iterator<Integer> iterator = new Iterator<>() {
Лишнее создание переменной

2020-05-19 07:38 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        Iterator<Integer> iterator = new Iterator<>() {
Лучше тоже вынести, как nested class

2020-05-19 07:38 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        var iterator = new Iterator<Integer>() {
Лишнее создание переменной

2020-05-19 07:38 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    private class Link {
static

2020-05-19 07:38 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        public int item;
геттеры и сеттеры

2020-05-19 07:38 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        public int item;
final

2020-05-19 07:38 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        public Link next = null;
Видимо тоже final и передавать в конструкторе?

2020-06-14 17:39 UTC, GranPecador commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        public Link next = null;
неее, он же изменяется и изначально всегда null

2020-06-17 10:52 UTC, Walingar requested changes

2020-06-17 10:52 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    int sizeMas = 0;
Что такое Mas??

2020-06-17 10:52 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +public class ArrayQueueImpl extends AbstractQueue<Integer> {
code-style

2020-06-17 10:52 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +            int temp = array[head++];
Что это за temp?

2020-06-20 13:26 UTC, Walingar requested changes

2020-06-20 13:26 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +                int[] newMas = new int[array.length - array.length / 4];
Что такое mas?

2020-06-20 14:39 UTC, Walingar approved these changes

2020-06-20 14:39 UTC, merged