HW4: Mednikov Artem
Walingar/java-is-2020 pull request #79
Opened 2020-04-08 20:00 UTC by be39na

2020-04-19 15:49 UTC, Walingar requested changes

2020-04-19 15:49 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    private static class Item {
Лучше nested классы в в конце писать

2020-04-19 15:49 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        LinkedQueueIterator(Item head) {
Отступ в одну пустую строчку должен быть перед конструктором

2020-04-19 15:49 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +            var next = current.getNext();
Можно сразу сделать return current.getNext()

2020-04-19 15:49 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        void setValue(int newValue) {
В очереди мы не хотим менять значений, поэтому это не нужно.

2020-04-19 15:49 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    private static class LinkedQueueIterator implements Iterator {
Не нужно использовать Raw Types

2020-04-19 15:49 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private int resizeCoefficient;
final. И это даже можно сделать константой

2020-04-19 15:49 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private class ArrayQueueIterator implements Iterator {
raw type

2020-04-19 15:49 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private class ArrayQueueIterator implements Iterator {
тоже в конце лучше писать класс

2020-04-19 15:49 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        queue[tail] = (Integer) item;
Тут не нужен каст

2020-04-19 15:49 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    public Integer poll() {
Получается, если сделаем много операци добавления, а потом бОльшую часть удалим, то останется выделенным много памяти :(

2020-04-19 15:49 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        if (size() == 0) {
Почему тут используется метод, а выше филд?

2020-06-20 13:29 UTC, Walingar requested changes

2020-06-20 13:29 UTC, Walingar commented on README.md
> +программа не потребляла много памяти.55
Зачем здесь 55?

2020-06-20 13:29 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        private Integer value;
final

2020-06-20 13:29 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +            this.nextItem = next;
this не нужен

2020-06-20 13:29 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +            this.nextItem = next;
this не нужен

2020-06-20 13:29 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    public Integer poll() {
Проблема с потребление памяти осталась

2020-06-25 08:55 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    public boolean offer(Integer Item) {
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2020-06-27 20:38 UTC, Walingar requested changes

2020-06-27 20:38 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    public Iterator iterator() {
Не следует использовать raw types. Укажи тип Generic

2020-06-27 20:38 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    public Iterator iterator() {
аналогично

2020-06-27 20:38 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    private final class Item {
static

2020-06-27 20:38 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        private Integer value;
final

2020-06-29 19:27 UTC, be39na commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    public Iterator iterator() {
Не уверен что понимаю как это пофиксить..

2020-06-30 06:17 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    public Iterator iterator() {
Да, у тебя проблема, что тут ожидается Iterator<Integer>, а LinkedQueueIterator имплементит Iterator<Item>, а должен Iterator<Integer>
P.S. Не забудь, что nested классы в конце должны быть

2020-06-30 21:39 UTC, Walingar approved these changes

2020-06-30 21:39 UTC, merged

2020-06-30 21:41 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    public Iterator iterator() {
Буду считать, что ты смог бы это исправить :)