HW:4 Rozanov Artem
Walingar/java-is-2020 pull request #86
Opened 2020-04-14 10:37 UTC by Rznov

2020-04-20 08:47 UTC, Walingar commented
Не нужно коммитить .DS_Store файлы

2020-04-20 08:53 UTC, Walingar requested changes

2020-04-20 08:53 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        return size() == values.length - 1 ? true : false;
Можно просто написать size() == values.length

2020-04-20 08:53 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        return size() == values.length - 1 ? true : false;
Притом, т.к. это часть имплементации, можно использовать другую часть: филд size

2020-04-20 08:53 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +            int newSize = Math.multiplyExact(values.length, 2);
Почему просто не умножить на 2?

2020-04-20 08:53 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        } catch (Exception e) {
Нехорошо ловить любой Exception

2020-04-20 08:53 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        private int value;
final

2020-04-20 08:53 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    private class Node {
Лучше стараться делать статические классы, чтобы случайно не обращаться к полям родителя.

2020-04-20 08:53 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +    private class Node {
Лучше писать nested классы внизу, как в соседнем файле

2020-06-11 05:31 UTC, Rznov commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        return size() == values.length - 1 ? true : false;
не совсем тебя понял

2020-06-11 05:32 UTC, Rznov commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +            int newSize = Math.multiplyExact(values.length, 2);
чтобы поймать переполнение, если оно произойдет

2020-06-11 05:34 UTC, Rznov commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +            int newSize = Math.multiplyExact(values.length, 2);
чтобы поймать переполнение, если оно произойдет

2020-06-17 13:59 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        return size() == values.length - 1 ? true : false;
Я говорю, что можно не вызывать метод size(), который выполняет доп проверки, а просто использовать size филд

2020-06-20 14:06 UTC, Rznov commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        return size() == values.length - 1 ? true : false;
понятно, но как лучше?

2020-06-20 14:43 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        return size() == values.length - 1 ? true : false;
А, у вас же size всегда расчитывается от head и tail, все ок. Сорри

2020-06-20 14:45 UTC, Walingar approved these changes
Обычно .gitignore общий не меняется для таких вещей как *txt или .DS_Store, т.к. это developer-specific настройки. Для такого обычно использую локальных `.git/info/exclude`, но это так, на будущее

2020-06-20 14:45 UTC, Walingar commented on temp/dir1/dir2/a.txt
> +Какая-то другая строчка
Этот файл тут не нужен

2020-06-20 14:45 UTC, merged