HW4: Klemesheva Alexandra
Walingar/java-is-2020 pull request #94
Opened 2020-04-14 18:56 UTC by ITLeopard

2020-04-20 08:58 UTC, Walingar requested changes

2020-04-20 08:58 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +    private int[] mas = new int[50000];
mas ? Это на каком языке?)

2020-04-20 08:58 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        return new Iterator<>() {
Лучше вынести это в nested class

2020-04-20 08:58 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +            System.out.println("Error! There is no place to insert new element");
Лучше такой вывод не делать. То, почему возвращается false описано в контракте

2020-04-20 08:58 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +            System.out.println("Nothing to poll! There are no elements in the queue");
Аналогично

2020-04-20 08:58 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +            System.arraycopy(mas, 1, mas, 0, size - 1);
Лучше использовать статический метод у Arrays

2020-04-20 08:58 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +            System.arraycopy(mas, 1, mas, 0, size - 1);
Получается, у тебя на каждый вызов poll копируется массив, это не хорошо

2020-04-20 08:58 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +public class ArrayQueueImpl extends AbstractQueue<Integer> {
Нужно сделать так, чтобы массив изменял свой размер. При добавлении в массив: если не хватает места - увеличиваем массив вдвое. При удалении: если элементов четверть, уменьшаем массив вдвое.

2020-04-20 08:58 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        private int value;
final

2020-04-20 08:58 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +            System.out.println("There are no elements in the queue");
Аналогично

2020-04-20 08:58 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +        return new Iterator<>() {
тоже лучше в nested class

2020-04-20 08:58 UTC, Walingar commented on src/main/java/queue/impl/LinkedQueueImpl.java
> +public class LinkedQueueImpl extends AbstractQueue<Integer> {
Тут хорошо!

2020-06-17 14:55 UTC, ITLeopard commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +            System.arraycopy(mas, 1, mas, 0, size - 1);
Это принципиально? Arrays.copyOf() не подходит, т.к. с помощью этого метода невозможно создать массив бОльшей длины, чем был.
Можно мне это зачесть так? Я видела, что у других людей зачтено, несмотря на то, что у них использован именно этот метод.

2020-06-20 09:04 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +            System.arraycopy(mas, 1, mas, 0, size - 1);
ok

2020-06-20 09:17 UTC, Walingar requested changes

2020-06-20 09:17 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +                int[] newMas = new int[lastIndex];
Что значит mas?

2020-06-20 09:17 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        if (lastIndex - firstIndex == 0) {
copy-paste

2020-06-20 09:44 UTC, ITLeopard commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        if (lastIndex - firstIndex == 0) {
Этот комментарий означает, что нужно создать отдельную переменную, хранящую lastIndex - firstIndex? Или ты говоришь, что эту часть я написала не сама, а подсмотрела?

2020-06-20 09:46 UTC, Walingar commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        if (lastIndex - firstIndex == 0) {
Я это использую обычно для указания того, чтор нужно вынести общую часть кода -  да. В твоем случае этот код уже вынесен даже) Его просто нужно использовать

2020-06-20 09:47 UTC, ITLeopard commented on src/main/java/queue/impl/ArrayQueueImpl.java
> +        if (lastIndex - firstIndex == 0) {
Хорошо, спасибо)

2020-06-20 13:29 UTC, Walingar approved these changes

2020-06-20 13:29 UTC, merged