Implement FileEncodingWriter and Reader
Walingar/java-is-2020 pull request #98
Opened 2020-04-15 09:46 UTC by Rznov

2020-04-20 10:11 UTC, Walingar requested changes

2020-04-20 10:11 UTC, Walingar commented on temp/dir1/dir2/a.txt
> +Какая-то другая строчка
Этот файл не нужно коммитить, он создается в процессе тестирования

2020-04-20 10:11 UTC, Walingar commented on src/main/java/impl/file/FileEncodingReaderImpl.java
> +import java.nio.file.Files;
Этот импорт не нужен

2020-04-20 10:11 UTC, Walingar commented on src/main/java/impl/file/FileEncodingReaderImpl.java
> +            throw new RuntimeException(e.getMessage());
Не очень хорошо бросать RuntimeException лучше что-то более специфичное

2020-04-20 10:11 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +import javax.sound.sampled.AudioFormat;
лишний импорт

2020-04-20 10:11 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            try (var writer = new FileWriter(file, fileEncoding)) {
Можно в одном try создавать несколько переменных

2020-04-20 10:11 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            e.printStackTrace();
Не следует использовать printStackTrace в продакшн коде.

2020-06-11 06:58 UTC, Rznov commented on temp/dir1/dir2/a.txt
> +Какая-то другая строчка
добавил *txt в gitignore и здесь тесты не прошли

2020-06-20 14:13 UTC, Rznov commented on temp/dir1/dir2/a.txt
> +Какая-то другая строчка
кидает ошибку impl.file.FileEncodingException: temp/dir1/dir2/a.txt (No such file or directory)

2020-06-20 14:35 UTC, Walingar commented on temp/dir1/dir2/a.txt
> +Какая-то другая строчка
Все верно, т.к. ваше решение работает неправильно

2020-06-20 15:21 UTC, Walingar requested changes

2020-06-20 15:21 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +    public void write(File file, InputStream data, Charset dataEncoding, Charset fileEncoding) {
Не создается новый файл, если нужно

2020-06-30 21:51 UTC, closed without merging